import * as fs from 'fs'
import * as path from 'path'
import * as crypto from 'crypto'
import type { Source } from './sources'
import type { CorpusSelectionItem } from './types'
import { resolveResearchDir } from '../research-paths'

export interface CorpusEntry {
  id: string
  title: string
  url: string
  openAccessUrl?: string
  doi?: string
  arxivId?: string
  pmid?: string
  authors?: string
  year?: number
  date?: string
  sourceTool?: string
  snippet?: string
  venue?: string
  citationCount?: number
  publicationType?: 'survey' | 'review' | 'benchmark' | 'method' | 'tool' | 'safety' | 'background' | 'unknown'
  tier: 'primary' | 'secondary' | 'background'
  screeningStatus?: 'raw' | 'selected' | 'rejected' | 'needs_review'
  /**
   * A screening decision explicitly pinned by a human (review panel) or the agent
   * (reject_corpus_items). screen_corpus/build_corpus MUST respect it and never resurrect
   * a manually rejected source nor silently drop a manually kept one. This is the fix for
   * the "reject → rebuild → screen → off-topic comes back" loop that forced the
   * topical_precision gate to be downgraded and let off-topic papers into the report.
   */
  pinnedStatus?: 'selected' | 'rejected'
  screeningReason?: string
  relevanceScore?: number
  recencyScore?: number
  authorityScore?: number
  topicalPrecisionScore?: number
  /**
   * Language-agnostic topical relevance (0–100) judged by the LLM, which reads the query and
   * the source in ANY language. This is the primary relevance signal when present: it replaces
   * the brittle lexical token-overlap heuristic that failed whenever the query language differed
   * from the source language (e.g. a Russian question over English web pages selected nothing).
   * `semanticQueryKey` binds the score to the exact question+sub-questions it was computed for,
   * so a re-screen for the same query reuses the cached score (free + deterministic) and a
   * changed query invalidates it.
   */
  semanticRelevanceScore?: number
  semanticOnTopic?: boolean
  semanticQueryKey?: string
  /**
   * Plan sub-questions (e.g. ["Q1","Q4"]) the LLM judged this source to cover, computed in
   * the same language-agnostic screening pass as `semanticRelevanceScore`. This is the PRIMARY
   * sub-topic signal: it works across languages, unlike lexical token overlap between a
   * (often non-English) plan and English titles, which left broad/quantum surveys tagged to
   * NO plan item and their plan rows uncovered. Bound to the query via `semanticQueryKey`.
   */
  semanticSubQuestions?: string[]
  readPriority?: 'high' | 'medium' | 'low'
  subQuestions?: string[]
  readStatus?: 'not_read' | 'queued' | 'read' | 'failed'
  readAt?: number
  readReason?: string
  status: 'candidate' | 'queued_full_text' | 'read' | 'rejected'
  score: number
  tags: string[]
  localPath?: string
  /** Cached per-source summary used in the report (generated by the LLM). */
  summary?: string
  /** Language of the cached summary ('ru' | 'en') so we can regenerate on language change. */
  summaryLang?: string
  addedAt: number
  updatedAt: number
}

export interface CorpusStats {
  total: number
  primary: number
  selected: number
  rejected: number
  needsReview: number
  queuedFullText: number
  read: number
  failed: number
  withDoi: number
  withArxiv: number
  selectedRead: number
  highPriority: number
  highPriorityRead: number
  reviewLike: number
  selectedReviewLike: number
  highCitation: number
}

export interface CorpusScreenOptions {
  question: string
  subQuestions?: string[]
  yearFrom?: number
  yearTo?: number
  /**
   * Day-precise window (YYYY-MM-DD). When present these take precedence over yearFrom/yearTo,
   * so sub-year requests ("last 3 months") are enforced at day granularity instead of being
   * floored to a calendar year. yearFrom/yearTo remain the fallback for undated-but-year-known
   * entries and for coarse year windows.
   */
  fromDate?: string
  toDate?: string
  maxSelected?: number
  /** Soft floor: promote the best on-topic items to reach this many selected. */
  minSelected?: number
  strictDateRange?: boolean
  /**
   * Topical-relevance strategy. 'academic' (default) keeps the ML/RL-aware precision
   * heuristic tuned for the science pipeline. 'general' (web research) judges relevance
   * generically from how well the source title/snippet covers the query terms, so the
   * gate actually filters off-topic pages for non-academic / non-ML topics.
   */
  researchKind?: 'general' | 'academic' | string
  /**
   * Extra topical vocabulary to fold into relevance/precision for GENERAL (web) research
   * only. In practice these are the English search queries the agent actually ran. The user
   * question is often in another language (e.g. Russian) than the English web pages it finds,
   * so matching sources against the Russian question alone drives topical precision to near
   * zero and nothing gets selected. Matching against the same English vocabulary used to find
   * the sources makes screening language-robust. Ignored for academic research to keep the
   * science pipeline byte-for-byte unchanged.
   */
  queryAugment?: string[]
}

/**
 * Minimum topical-precision score for a source to be eligible for the `selected` set.
 * The floor-promotion in screenCorpus and the `topical_precision` quality gate share this
 * single threshold, so a source promoted to hit the minimum count can never afterwards be
 * flagged (and force-downgraded) by the gate. Keeping them in sync is what makes the
 * topical_precision gate genuinely passable by re-screening instead of only via downgrade.
 */
export const MIN_SELECTABLE_TOPICAL_PRECISION = 45

/**
 * Stable cache key for a screening query (question + sub-questions), language- and
 * order-normalized. Used to bind a cached semantic relevance score to the exact query it was
 * computed for, so re-screening the same query is free and changing the query invalidates it.
 */
export function semanticQueryKey(question: string, subQuestions?: string[]): string {
  const norm = [String(question || ''), ...((subQuestions || []).map(String))]
    .join(' ¶ ')
    .toLowerCase()
    .replace(/\s+/g, ' ')
    .trim()
  return crypto.createHash('sha1').update(norm).digest('hex').slice(0, 16)
}

function researchDir(workspace: string, outputDir?: string): string {
  return resolveResearchDir(workspace, outputDir)
}

export function corpusPath(workspace: string, outputDir?: string): string {
  return path.join(researchDir(workspace, outputDir), 'corpus.jsonl')
}

function normalizeTitle(title: string): string {
  return title.toLowerCase().replace(/[^a-z0-9а-яё]+/gi, ' ').trim().replace(/\s+/g, ' ')
}

function slugHash(input: string): string {
  return crypto.createHash('sha1').update(input).digest('hex').slice(0, 10)
}

export function extractDoi(text: string): string | undefined {
  const doi = text.match(/\b10\.\d{4,9}\/[-._;()/:A-Z0-9]+/i)?.[0]
  return doi ? doi.replace(/[.,;)\]]+$/, '') : undefined
}

export function extractArxivId(text: string): string | undefined {
  const url = text.match(/arxiv\.org\/(?:abs|pdf|html)\/([^?\s#]+)/i)?.[1]
  if (url) return url.replace(/\.pdf$/i, '')
  const explicit = text.match(/\barxiv\s*:\s*([a-z-]+\/\d{7}(?:v\d+)?|\d{4}\.\d{4,5}(?:v\d+)?)\b/i)?.[1]
  if (explicit) return explicit
  const doiArxiv = text.match(/\b10\.48550\/arxiv\.([a-z-]+\/\d{7}(?:v\d+)?|\d{4}\.\d{4,5}(?:v\d+)?)\b/i)?.[1]
  return doiArxiv
}

export function extractPmid(text: string): string | undefined {
  return text.match(/\bPMID[:\s]+(\d{5,12})\b/i)?.[1] ?? text.match(/pubmed\.ncbi\.nlm\.nih\.gov\/(\d+)/i)?.[1]
}

function keyFor(entry: Pick<CorpusEntry, 'doi' | 'arxivId' | 'pmid' | 'url' | 'title'>): string {
  if (entry.doi) return `doi:${entry.doi.toLowerCase()}`
  if (entry.arxivId) return `arxiv:${entry.arxivId.toLowerCase().replace(/v\d+$/, '')}`
  if (entry.pmid) return `pmid:${entry.pmid}`
  if (entry.url) return `url:${entry.url.toLowerCase().replace(/\/$/, '')}`
  return `title:${normalizeTitle(entry.title)}`
}

export function loadCorpus(workspace: string, outputDir?: string): CorpusEntry[] {
  const p = corpusPath(workspace, outputDir)
  if (!fs.existsSync(p)) return []
  try {
    return fs.readFileSync(p, 'utf-8')
      .split('\n')
      .filter(Boolean)
      .map((line) => normalizeEntry(JSON.parse(line) as CorpusEntry))
  } catch { return [] }
}

function normalizeEntry(entry: CorpusEntry): CorpusEntry {
  const readStatus = entry.readStatus
    ?? (entry.status === 'read' ? 'read' : entry.status === 'queued_full_text' ? 'queued' : entry.status === 'rejected' ? 'failed' : 'not_read')
  const screeningStatus = entry.screeningStatus ?? (entry.status === 'rejected' ? 'rejected' : 'raw')
  return {
    ...entry,
    publicationType: entry.publicationType ?? classifyPublicationType(entry),
    screeningStatus,
    readStatus,
    subQuestions: Array.isArray(entry.subQuestions) ? entry.subQuestions : [],
  }
}

export function saveCorpus(workspace: string, entries: CorpusEntry[], outputDir?: string): void {
  const p = corpusPath(workspace, outputDir)
  fs.mkdirSync(path.dirname(p), { recursive: true })
  const sorted = [...entries].sort((a, b) => b.score - a.score || b.updatedAt - a.updatedAt)
  fs.writeFileSync(p, sorted.map((e) => JSON.stringify(e)).join('\n') + (sorted.length ? '\n' : ''), 'utf-8')
}

function scoreEntry(entry: CorpusEntry): number {
  let score = 10
  if (entry.doi) score += 15
  if (entry.arxivId) score += 12
  if (entry.pmid) score += 12
  if (entry.url.includes('arxiv.org') || entry.url.includes('doi.org') || entry.url.includes('pubmed')) score += 8
  if ((entry.citationCount ?? 0) >= 50) score += 8
  if ((entry.citationCount ?? 0) >= 200) score += 8
  if (entry.publicationType === 'survey' || entry.publicationType === 'review') score += 12
  if ((entry.topicalPrecisionScore ?? 0) < 35) score -= 20
  if (entry.snippet && entry.snippet.length > 80) score += 5
  if (entry.year && entry.year >= new Date().getFullYear() - 1) score += 6
  if (entry.tier === 'primary') score += 10
  score += Math.round(entry.relevanceScore ?? 0)
  score += Math.round((entry.authorityScore ?? 0) / 2)
  score += Math.round((entry.recencyScore ?? 0) / 2)
  if (entry.screeningStatus === 'selected') score += 20
  if (entry.readPriority === 'high') score += 8
  if (entry.screeningStatus === 'rejected') score -= 100
  return score
}

export function sourceToCorpusEntry(source: Source | Omit<Source, 'idx'>, tags: string[] = []): CorpusEntry {
  const now = Date.now()
  const text = `${source.title}\n${source.url}\n${source.snippet ?? ''}`
  const doi = extractDoi(text)
  const arxivId = extractArxivId(text)
  const pmid = extractPmid(text)
  const venue = extractLineValue(text, 'Venue')
  const citationCount = extractNumberLineValue(text, 'Citations')
  const year = Number(String(source.date ?? '').match(/\b(19|20)\d{2}\b/)?.[0]) || undefined
  const tier: CorpusEntry['tier'] = source.sourceTool?.includes('web') ? 'secondary' : 'primary'
  const id = slugHash(keyFor({ title: source.title, url: source.url, doi, arxivId, pmid }))
  const entry: CorpusEntry = {
    id,
    title: source.title,
    url: source.url,
    openAccessUrl: source.openAccessUrl,
    doi,
    arxivId,
    pmid,
    authors: source.authors,
    venue,
    citationCount,
    year,
    date: source.date,
    sourceTool: source.sourceTool,
    snippet: source.snippet,
    tier,
    publicationType: 'unknown',
    screeningStatus: 'raw',
    readStatus: 'not_read',
    subQuestions: [],
    status: 'candidate',
    score: 0,
    tags,
    addedAt: now,
    updatedAt: now,
  }
  entry.publicationType = classifyPublicationType(entry)
  entry.score = scoreEntry(entry)
  return entry
}

export function mergeCorpusEntries(existing: CorpusEntry[], incoming: CorpusEntry[]): { entries: CorpusEntry[]; added: number; updated: number } {
  const byKey = new Map<string, CorpusEntry>()
  for (const e of existing) byKey.set(keyFor(e), e)
  let added = 0
  let updated = 0
  for (const next of incoming) {
    const k = keyFor(next)
    const prev = byKey.get(k)
    if (!prev) {
      byKey.set(k, next)
      added++
    } else {
      // A freshly-built incoming entry carries default/raw progress (readStatus
      // 'not_read', screeningStatus 'raw', no localPath). Spreading it over `prev`
      // would wipe screening/read progress accumulated during the run — which made
      // a rebuild silently lose selections and reads, and left status='read' with
      // readStatus='not_read' (an inconsistency that loops the reader). Keep the
      // workflow-progress fields sticky so re-merges never regress them.
      const keepReadStatus =
        prev.readStatus === 'read' || prev.readStatus === 'failed' || prev.readStatus === 'queued'
          ? prev.readStatus
          : (next.readStatus ?? prev.readStatus)
      const keepScreening =
        prev.screeningStatus && prev.screeningStatus !== 'raw'
          ? prev.screeningStatus
          : (next.screeningStatus ?? prev.screeningStatus)
      byKey.set(k, {
        ...prev,
        ...Object.fromEntries(Object.entries(next).filter(([, v]) => v !== undefined && v !== '')),
        id: prev.id,
        tags: [...new Set([...(prev.tags || []), ...(next.tags || [])])],
        status: prev.status === 'read' ? 'read' : next.status,
        screeningStatus: keepScreening,
        readStatus: keepReadStatus,
        readPriority: prev.readPriority ?? next.readPriority,
        localPath: prev.localPath ?? next.localPath,
        readReason: prev.readReason ?? next.readReason,
        subQuestions: prev.subQuestions?.length ? prev.subQuestions : (next.subQuestions ?? []),
        score: Math.max(prev.score, next.score),
        addedAt: prev.addedAt,
        updatedAt: Date.now(),
      } as CorpusEntry)
      updated++
    }
  }
  return { entries: [...byKey.values()], added, updated }
}

export function addSourcesToCorpus(workspace: string, sources: Array<Source | Omit<Source, 'idx'>>, tags: string[] = [], outputDir?: string): { entries: CorpusEntry[]; added: number; updated: number } {
  const existing = loadCorpus(workspace, outputDir)
  const incoming = sources.filter((s) => s.title && s.url).map((s) => sourceToCorpusEntry(s, tags))
  const merged = mergeCorpusEntries(existing, incoming)
  saveCorpus(workspace, merged.entries, outputDir)
  return merged
}

export function corpusStats(workspace: string, outputDir?: string): CorpusStats {
  const entries = loadCorpus(workspace, outputDir)
  const selected = entries.filter((e) => e.screeningStatus === 'selected')
  const highPriority = entries.filter((e) => e.screeningStatus === 'selected' && e.readPriority === 'high')
  return {
    total: entries.length,
    primary: entries.filter((e) => e.tier === 'primary').length,
    selected: selected.length,
    rejected: entries.filter((e) => e.screeningStatus === 'rejected').length,
    needsReview: entries.filter((e) => e.screeningStatus === 'needs_review').length,
    queuedFullText: entries.filter((e) => e.readStatus === 'queued' || e.status === 'queued_full_text').length,
    read: entries.filter((e) => e.readStatus === 'read' || e.status === 'read').length,
    failed: entries.filter((e) => e.readStatus === 'failed').length,
    withDoi: entries.filter((e) => !!e.doi).length,
    withArxiv: entries.filter((e) => !!e.arxivId).length,
    selectedRead: selected.filter((e) => e.readStatus === 'read' || e.status === 'read').length,
    highPriority: highPriority.length,
    highPriorityRead: highPriority.filter((e) => e.readStatus === 'read' || e.status === 'read').length,
    reviewLike: entries.filter(isReviewLike).length,
    selectedReviewLike: selected.filter(isReviewLike).length,
    highCitation: entries.filter((e) => (e.citationCount ?? 0) >= 50).length,
  }
}

export function listCorpus(workspace: string, max = 20, outputDir?: string): string {
  const entries = loadCorpus(workspace, outputDir).slice(0, Math.max(1, Math.min(100, max)))
  if (entries.length === 0) return 'Corpus is empty. Use build_corpus or add_to_corpus after search.'
  const stats = corpusStats(workspace, outputDir)
  const lines = [`Corpus: ${stats.total} items (${stats.primary} primary, ${stats.queuedFullText} queued full text, ${stats.read} read)\n`]
  entries.forEach((e, i) => {
    lines.push([
      `${i + 1}. ${e.title}`,
      `   ID: ${e.id} | score=${e.score} | ${e.tier} | screen=${e.screeningStatus ?? 'raw'} | read=${e.readStatus ?? e.status}`,
      e.year ? `   Year: ${e.year}` : null,
      e.doi ? `   DOI: ${e.doi}` : null,
      e.arxivId ? `   arXiv: ${e.arxivId}` : null,
      e.citationCount !== undefined ? `   Citations: ${e.citationCount}` : null,
      e.publicationType ? `   Type: ${e.publicationType}` : null,
      `   URL: ${e.url}`,
      e.snippet ? `   Snippet: ${e.snippet.slice(0, 220)}` : null,
    ].filter(Boolean).join('\n'))
  })
  return lines.join('\n\n')
}

export function queueFullText(workspace: string, ids?: string[], outputDir?: string): string {
  const entries = loadCorpus(workspace, outputDir)
  const wanted = new Set((ids || []).map(String))
  let changed = 0
  for (const e of entries) {
    if (wanted.size === 0 || wanted.has(e.id)) {
      if (e.status === 'candidate') {
        e.status = 'queued_full_text'
        e.readStatus = 'queued'
        e.updatedAt = Date.now()
        changed++
      }
    }
  }
  saveCorpus(workspace, entries, outputDir)
  return `Queued ${changed} corpus item(s) for full-text reading.`
}

export function rankCorpus(workspace: string, outputDir?: string): string {
  const entries = loadCorpus(workspace, outputDir).map((e) => ({ ...e, score: scoreEntry(e), updatedAt: Date.now() }))
  saveCorpus(workspace, entries, outputDir)
  return listCorpus(workspace, 30, outputDir)
}

function tokenizeQuery(text: string): string[] {
  const stop = new Set(['the', 'and', 'for', 'with', 'from', 'into', 'about', 'какие', 'какой', 'как', 'что', 'для', 'или', 'это', 'over', 'last'])
  return String(text || '').toLowerCase()
    .replace(/[^a-z0-9а-яё+.-]+/gi, ' ')
    .split(/\s+/)
    .map((t) => t.trim())
    .filter((t) => t.length >= 3 && !stop.has(t))
}

// Words that describe the DELIVERABLE or the umbrella field, not a specific sub-topic.
// They appear in (almost) every RL/ML sub-question, so matching on them assigns a source
// to every plan item and defeats the point. Excluded from sub-question discrimination.
const SUBQ_GENERIC = new Set([
  'survey', 'surveys', 'review', 'reviews', 'overview', 'systematic', 'tutorial', 'taxonomy',
  'обзор', 'обзорные', 'обзорных', 'обзорная', 'статьи', 'статья', 'статей', 'работы', 'публикации',
  'reinforcement', 'learning', 'deep', 'general', 'algorithm', 'algorithms', 'method', 'methods',
  'model', 'models', 'paper', 'papers', 'research', 'study', 'studies', 'approach', 'approaches',
  'направлениям', 'направления', 'общим', 'общие', 'основные',
])

/** Split hyphenated compounds into their parts too, so "quantum-classical" also yields
 *  the discriminative bare terms "quantum"/"classical" that appear in English titles. */
function expandTokens(text: string): string[] {
  const base = tokenizeQuery(text)
  const out = new Set<string>()
  for (const t of base) {
    out.add(t)
    if (t.includes('-')) for (const part of t.split('-')) if (part.length >= 3) out.add(part)
  }
  return [...out]
}

/** Does `text` contain the discriminative term, tolerant of trivial plural/stem variation
 *  ("survey" vs "surveys", "robotic" vs "robotics")? */
function docHasTerm(text: string, term: string): boolean {
  if (text.includes(term)) return true
  if (term.endsWith('s') && term.length > 4 && text.includes(term.slice(0, -1))) return true
  if (!term.endsWith('s') && term.length >= 4 && text.includes(term + 's')) return true
  return false
}

/**
 * Assign a corpus entry to the plan sub-questions it actually covers — robustly across
 * languages. The previous approach matched raw sub-question tokens against the (often
 * English) title, so a Cyrillic plan phrase like "квантовому RL" never matched "Quantum
 * Reinforcement Learning" and the survey ended up tagged to NO sub-question (sub=[]),
 * hence uncovered plan items even though the paper was in the corpus. Fixes:
 *   - expand hyphenated compounds ("quantum-classical" → quantum, classical);
 *   - drop deliverable/umbrella words (survey/review/reinforcement/learning/RL/general/…)
 *     that occur in every sub-question and carry no discriminative signal;
 *   - drop terms shared by most sub-questions (data-frequency filter);
 *   - if nothing specific matches, fall back to the plan's GENERAL sub-topic (if any),
 *     so a broad RL survey lands on "general RL" instead of nowhere.
 */
function assignSubQuestions(text: string, subQuestions: string[]): string[] {
  const n = subQuestions.length
  if (n === 0) return []
  const perQ = subQuestions.map((q) =>
    new Set(expandTokens(q).filter((t) => t.length >= 3 && !SUBQ_GENERIC.has(t) && !/^\d+$/.test(t))),
  )
  const df = new Map<string, number>()
  for (const s of perQ) for (const t of s) df.set(t, (df.get(t) ?? 0) + 1)
  const tooCommon = Math.max(2, Math.ceil(n / 2))
  const scored = perQ.map((terms, i) => {
    let hits = 0
    for (const t of terms) {
      if ((df.get(t) ?? 0) >= tooCommon) continue
      if (docHasTerm(text, t)) hits++
    }
    return { id: `Q${i + 1}`, hits }
  })
  const matched = scored.filter((x) => x.hits > 0).sort((a, b) => b.hits - a.hits).slice(0, 3).map((x) => x.id)
  if (matched.length > 0) return matched
  // Catch-all: a broad RL survey that matched no specific sub-topic belongs to the
  // "general" plan item, if the plan has one (English "general" or Russian "общ…").
  const generalIdx = subQuestions.findIndex((q) => /\bgeneral\b|общ|общих|общими|широк/i.test(q))
  return generalIdx >= 0 ? [`Q${generalIdx + 1}`] : []
}

function extractLineValue(text: string, label: string): string | undefined {
  return text.match(new RegExp(`^\\s*${label}:\\s*(.+)$`, 'im'))?.[1]?.trim()
}

function extractNumberLineValue(text: string, label: string): number | undefined {
  const value = extractLineValue(text, label)
  if (!value) return undefined
  const n = Number(value.replace(/[^\d.-]+/g, ''))
  return Number.isFinite(n) ? n : undefined
}

function classifyPublicationType(entry: Pick<CorpusEntry, 'title' | 'snippet' | 'venue' | 'url'>): CorpusEntry['publicationType'] {
  const text = `${entry.title} ${entry.snippet ?? ''} ${entry.venue ?? ''} ${entry.url ?? ''}`.toLowerCase()
  if (/\b(systematic\s+review|meta[- ]analysis|survey|review|overview|state[- ]of[- ]the[- ]art)\b/i.test(text)) return /survey/i.test(text) ? 'survey' : 'review'
  if (/\bbenchmark|leaderboard|evaluation suite|dataset\b/i.test(text)) return 'benchmark'
  if (/\bframework|library|toolkit|open-source|github|trl|openrlhf|verl|vllm\b/i.test(text)) return 'tool'
  if (/\bsafety|alignment|poison|bias|jailbreak|harm|robustness\b/i.test(text)) return 'safety'
  if (/\bmethod|approach|algorithm|training|optimization|fine[- ]tuning|post[- ]training\b/i.test(text)) return 'method'
  return 'unknown'
}

export function isReviewLike(entry: Pick<CorpusEntry, 'publicationType' | 'title' | 'snippet'>): boolean {
  return entry.publicationType === 'survey'
    || entry.publicationType === 'review'
    || /\b(survey|review|overview|systematic|meta[- ]analysis|state[- ]of[- ]the[- ]art)\b/i.test(`${entry.title} ${entry.snippet ?? ''}`)
}

/**
 * Generic topical precision for general (web) research. The ML/RL heuristic below
 * only understands LLM/RL vocabulary, so for any non-ML topic it returns a flat 50
 * and stops filtering. Here we judge relevance from how much of the query vocabulary
 * the source's own title/snippet actually covers — a source that shares none of the
 * query terms is off-topic and must be rejected, regardless of recency or authority.
 */
function genericTopicPrecisionFor(entry: CorpusEntry, queryText: string): { score: number; blockers: string[] } {
  const text = `${entry.title} ${entry.snippet ?? ''}`.toLowerCase()
  // Match on distinctive content words only: drop pure numbers (bare years like 2024/2025
  // otherwise let a date-only page look on-topic) and 1–2 char tokens.
  const terms = [...new Set(tokenizeQuery(queryText))].filter((t) => t.length >= 3 && !/^\d+$/.test(t))
  if (terms.length === 0) return { score: 60, blockers: [] }
  const hits = terms.filter((t) => text.includes(t)).length
  if (hits === 0) {
    return { score: 8, blockers: ['Off-topic: none of the query terms appear in the source title/snippet'] }
  }
  // Saturating count, NOT coverage-over-vocabulary: a handful of distinct topical hits is
  // enough to be clearly on-topic. Dividing by the full vocabulary size (as before) meant a
  // large or cross-language query vocabulary pushed every source below the selection floor,
  // so nothing was ever selected — the "0 selected / screen_corpus loop" symptom.
  const score = Math.max(0, Math.min(100, 30 + hits * 12))
  return { score, blockers: [] }
}

function topicPrecisionFor(entry: CorpusEntry, queryText: string, researchKind?: string, scopeQuery?: string): { score: number; blockers: string[] } {
  // General (web) research is not RL/LLM-specific, so the academic heuristic would be a
  // no-op (flat 50) and let junk through. Use the generic query-coverage relevance instead.
  if (String(researchKind || 'academic') === 'general') return genericTopicPrecisionFor(entry, queryText)
  // IMPORTANT: do NOT include entry.tags here. `build_corpus` applies the same
  // query-level topic tags (e.g. "RL,LLM,RLHF,DPO,...") uniformly to every source,
  // so trusting tags would make every item look on-topic (precision=100) and fully
  // defeat this gate — letting astrophysics/quantum/math papers pass screening.
  // Topical precision must be judged from the source's own title + snippet only.
  const text = `${entry.title} ${entry.snippet ?? ''}`.toLowerCase()
  // Intent (what the study is ABOUT) must come from the MAIN research question, not the
  // merged sub-question text. Otherwise a single LLM-flavoured sub-topic (e.g. "RLHF for
  // LLM alignment") turns the whole run into "RL AND LLM", and every legitimate RL-only
  // survey (multi-agent RL, quantum RL, robotics RL) gets rejected as "missing RL+LLM
  // intersection" — the exact reason broad-RL runs leave topics uncovered.
  const query = String(scopeQuery ?? queryText).toLowerCase()
  const wantsLlm = /\b(llm|large language model|language models?|chatgpt|reasoning model|post-training|post training)\b/i.test(query)
  const wantsRl = /\b(reinforcement learning|rlhf|rlvr|grpo|dpo|ppo|rloo|\brl\b|reward|policy optimization|preference optimization)\b/i.test(query)
  const hasLlm = /\b(llm|large language model|language models?|chatgpt|reasoning model|post-training|post training)\b/i.test(text)
  const hasRl = /\b(reinforcement learning|rlhf|rlvr|grpo|dpo|ppo|rloo|\brl\b|reward|policy optimization|preference optimization)\b/i.test(text)
  const blockers: string[] = []
  let score = 50
  if (wantsLlm) score += hasLlm ? 25 : -30
  if (wantsRl) score += hasRl ? 30 : -35
  if (wantsLlm && wantsRl && !(hasLlm && hasRl)) blockers.push('Missing required RL+LLM topical intersection')
  if (/\b(vulnerability|chemistry|speech synthesis|image restoration|constructional semantics|medical applications|gravitational waves)\b/i.test(text)) {
    score -= 30
    blockers.push('Likely off-topic for requested research scope')
  }
  return { score: Math.max(0, Math.min(100, score)), blockers }
}

function relevanceFor(entry: CorpusEntry, terms: string[], subQuestions: string[], queryText: string, researchKind?: string, semanticScore?: number, scopeQuery?: string, semanticSubQs?: string[]): { score: number; matched: string[]; subQs: string[]; topicalPrecision: number; blockers: string[] } {
  const text = `${entry.title} ${entry.snippet ?? ''} ${entry.authors ?? ''}`.toLowerCase()
  const matched = [...new Set(terms.filter((t) => text.includes(t)))]
  const rlBoost = ['reinforcement', 'learning', 'rl', 'rlhf', 'dpo', 'ppo', 'reward', 'policy', 'q-learning', 'offline', 'safe', 'robot', 'marl', 'agent', 'verifiable'].filter((t) => text.includes(t))
  // Prefer the LLM's language-agnostic plan-coverage assignment; fall back to the lexical
  // matcher only when the LLM has not assigned anything (no server / empty coverage).
  const subQs = (semanticSubQs && semanticSubQs.length) ? semanticSubQs : assignSubQuestions(text, subQuestions)
  // Language-agnostic path: when the LLM has judged this source against the query, that score
  // IS the topical relevance — no token overlap required, so it works across any language pair.
  // The lexical heuristic below is only the offline fallback (no server / not yet scored).
  if (typeof semanticScore === 'number' && Number.isFinite(semanticScore)) {
    const sem = Math.max(0, Math.min(100, Math.round(semanticScore)))
    return {
      score: sem,
      matched,
      subQs: subQs.length ? subQs : subQuestions.map((_, i) => `Q${i + 1}`).slice(0, 3),
      topicalPrecision: sem,
      blockers: sem < 30 ? ['Semantically off-topic for the research question (LLM-judged)'] : [],
    }
  }
  const precision = topicPrecisionFor(entry, queryText, researchKind, scopeQuery)
  return {
    score: Math.min(100, matched.length * 7 + rlBoost.length * 8 + subQs.length * 8 + Math.round(precision.score * 0.25)),
    matched,
    subQs,
    topicalPrecision: precision.score,
    blockers: precision.blockers,
  }
}

/** Parse a corpus entry's publication date to an ISO YYYY-MM-DD, if determinable. */
function entryIsoDate(entry: CorpusEntry): string | null {
  if (entry.date) {
    const m = String(entry.date).match(/(\d{4})-(\d{2})-(\d{2})/)
    if (m) return `${m[1]}-${m[2]}-${m[3]}`
    const d = new Date(entry.date)
    if (!Number.isNaN(d.getTime())) return d.toISOString().slice(0, 10)
  }
  return null
}

/**
 * Whether a genuinely SUB-ANNUAL window was requested (e.g. "last 3 months"), for which a
 * year-only or undated source cannot be confirmed in-range and must be demoted.
 *
 * A range aligned to whole-year boundaries — fromDate = YYYY-01-01 AND toDate = YYYY-12-31 —
 * is really just a YEAR range (e.g. 2024–2026), even though intake expresses it with day
 * boundaries. For it, a year-only source date is sufficient, so it is NOT a day window.
 * Treating "2024-01-01..2026-12-31" as day-precise wrongly demoted every undated survey to
 * needs_review and left whole plan sub-topics (reasoning, quantum, robotics) uncovered.
 */
function hasDayWindow(opts: CorpusScreenOptions): boolean {
  const from = opts.fromDate && /^\d{4}-\d{2}-\d{2}$/.test(opts.fromDate) ? opts.fromDate : null
  const to = opts.toDate && /^\d{4}-\d{2}-\d{2}$/.test(opts.toDate) ? opts.toDate : null
  if (!from && !to) return false
  const fromWholeYear = !from || /^\d{4}-01-01$/.test(from)
  const today = new Date().toISOString().slice(0, 10)
  // A toDate at/after today is an OPEN "…up to the present" bound, not a mid-year cutoff: nothing
  // can be published after today, so a year-only date IS enough to confirm the source falls in the
  // window. Treat it like a whole-year upper edge (same as Dec-31). This is what makes a request
  // like "статьи за 2026" — which intake expresses as from=2026-01-01, to=<today> — a COARSE year
  // range rather than a strict day window. Without this, every year-only 2026 survey was demoted to
  // needs_review ("No day-precise date"), dropped from the selectable pool, and the run could not
  // select enough sources — it then looped on duplicate searches/screens and hung.
  const toWholeYear = !to || /^\d{4}-12-31$/.test(to) || to >= today
  // Both edges land on year boundaries (or an open "to present" upper edge) → coarse year range.
  if (fromWholeYear && toWholeYear) return false
  return true
}

/**
 * Is the entry outside the requested window? Prefers day-precision (fromDate/toDate)
 * when the entry has a real date, and falls back to year bounds otherwise. Undated
 * entries are NOT flagged here — they are demoted (never auto-selected) separately so
 * they can still be used deliberately rather than silently dropped ("resolve then demote").
 */
function outsideRequestedWindow(entry: CorpusEntry, opts: CorpusScreenOptions): boolean {
  const iso = entryIsoDate(entry)
  if (iso && hasDayWindow(opts)) {
    if (opts.fromDate && iso < opts.fromDate) return true
    if (opts.toDate && iso > opts.toDate) return true
    return false
  }
  if (entry.year && (opts.yearFrom || opts.yearTo)) {
    if (opts.yearFrom && entry.year < opts.yearFrom) return true
    if (opts.yearTo && entry.year > opts.yearTo) return true
    return false
  }
  return false
}

/** Publisher hosts whose landing pages are typically paywalled AND often carry no clean
 * date — for the science pipeline we prefer open, dated indexes (arXiv/OpenAlex/…). */
const CLOSED_PUBLISHER_RE = /(?:springer|sciencedirect|elsevier|ieeexplore|ieee\.org|dl\.acm\.org|onlinelibrary\.wiley|tandfonline|jstor|sagepub|cambridge\.org|academic\.oup|oup\.com|researchgate|annualreviews)/i
const OPEN_SCHOLARLY_TOOL_RE = /arxiv|openalex|semantic|crossref|pubmed|biorxiv/i
// Non-scholarly hosts (blogs/aggregators): even when a post is titled "… survey", it is not a
// citable review AND typically not cleanly readable full text. Never worth a selection slot in
// an academic run.
const NON_SCHOLARLY_HOST_RE = /(?:medium\.com|towardsdatascience|substack|blogspot|wordpress|dev\.to|kaggle\.com|reddit\.com|quora\.com|linkedin\.com|x\.com|twitter\.com|facebook\.com|youtube\.com|youtu\.be|t\.me|telegram|siliconflow|sebastianraschka|analyticsvidhya|kdnuggets|geeksforgeeks|freecodecamp|hackernoon|marktechpost)/i
// SEO / listicle / blog-note titles ("Ultimate Guide", "The 2026 List", "Top 10 …",
// "Reading Notes", "Best … in 2026"): not citable scholarly work. Only treated as
// non-scholarly for UNDATED web pages (a real dated paper with such a title is rare and kept).
const NON_SCHOLARLY_TITLE_RE = /\b(ultimate guide|cheat ?sheet|reading notes|the (?:19|20)\d{2} list|best\b[^.]{0,50}\b(?:19|20)\d{2}\b|top\s+\d+\b|tutorial)\b/i

/** Open, readable, well-dated scholarly source (arXiv id, an OA URL, or an open index tool). */
function isOpenScholarly(entry: CorpusEntry): boolean {
  if (entry.arxivId) return true
  if (entry.openAccessUrl) return true
  return OPEN_SCHOLARLY_TOOL_RE.test(entry.sourceTool ?? '')
}

function isClosedPublisher(entry: CorpusEntry): boolean {
  return CLOSED_PUBLISHER_RE.test(entry.url ?? '')
}

/** Likely NOT retrievable as clean full text — paywalled publisher landing page or a blog.
 *  Selecting these wastes a slot and shows up as an "unavailable" source in the report. */
function likelyUnreadable(entry: CorpusEntry): boolean {
  if (entry.arxivId || entry.openAccessUrl) return false
  return isClosedPublisher(entry) || NON_SCHOLARLY_HOST_RE.test(entry.url ?? '')
}

/**
 * Heuristic: a blog / social / SEO / listicle page that is rarely a citable scholarly source.
 * The LLM screener rates topical relevance only (it never judges authority), so a LinkedIn post
 * or an "Ultimate Guide … 2026" can score 90+. This flag lets the academic pipeline RANK such
 * pages below real reviews (a soft nudge, `sourcePreferenceDelta`) — it never excludes them.
 * The user stays in control of which sources are used via the New Research dialog. Real papers
 * (arXiv id or a resolved open-access URL) are never flagged; only clearly non-academic web pages.
 */
function isNonScholarlySource(entry: CorpusEntry): boolean {
  if (entry.arxivId || entry.openAccessUrl) return false
  const url = entry.url ?? ''
  if (NON_SCHOLARLY_HOST_RE.test(url)) return true
  if (NON_SCHOLARLY_TITLE_RE.test(entry.title ?? '') && !entryIsoDate(entry)) return true
  return false
}

/**
 * Score nudge for the ACADEMIC pipeline: prefer open, dated sources (arXiv/OpenAlex) and
 * down-rank closed publisher landing pages that we cannot read and that are usually undated
 * (Springer/Elsevier/IEEE/ACM/Wiley…). No effect on general (web) research.
 */
function sourcePreferenceDelta(entry: CorpusEntry, researchKind?: string): number {
  if (String(researchKind || 'academic') !== 'academic') return 0
  let d = 0
  if (isOpenScholarly(entry)) d += 8
  else if (isClosedPublisher(entry)) d -= 12
  // Blog/social/SEO-listicle pages ("Ultimate Guide 2026", LinkedIn notes) are rarely citable
  // scholarly work. We do NOT exclude them — the user controls sources explicitly in the New
  // Research dialog — but in an academic run we rank them below real, retrievable reviews so
  // arXiv/OA surveys win selection slots when both are available.
  if (isNonScholarlySource(entry)) d -= 16
  return d
}

function recencyFor(entry: CorpusEntry, yearFrom?: number, yearTo?: number): number {
  if (!entry.year) return 20
  if (yearFrom && entry.year < yearFrom) return 0
  if (yearTo && entry.year > yearTo) return 20
  const current = new Date().getFullYear()
  return Math.max(15, Math.min(100, 100 - Math.max(0, current - entry.year) * 12))
}

function authorityFor(entry: CorpusEntry): number {
  let score = 20
  if (entry.doi) score += 20
  if (entry.arxivId) score += 20
  if ((entry.citationCount ?? 0) >= 25) score += 10
  if ((entry.citationCount ?? 0) >= 100) score += 10
  if (isReviewLike(entry)) score += 20
  if (/benchmark|nature|neurips|iclr|icml|acl|emnlp|naacl|science/i.test(`${entry.title} ${entry.snippet ?? ''} ${entry.venue ?? ''}`)) score += 20
  if (/openalex|semantic|crossref|pubmed|arxiv/i.test(entry.sourceTool ?? '')) score += 10
  return Math.min(100, score)
}

/**
 * Lightweight LEXICAL relevance for a single entry, used only to PRIORITIZE which corpus items the
 * budget-limited LLM semantic screener should score first. Ranking by this puts the candidates most
 * likely to be selected at the front, so the top of the final ranking is always LLM-validated —
 * unlike the old "count shared query words" heuristic, which was near-random for a cross-language
 * query (Russian question vs English titles) and spent the budget on tangential items.
 * Mirrors the screener's own term/relevance logic; no semantic/recency input (that's the point).
 */
export function lexicalRelevancePreScore(
  entry: CorpusEntry,
  question: string,
  subQuestions?: string[],
  researchKind?: string,
): number {
  const queryText = [question, ...(subQuestions || [])].join(' ')
  const terms = tokenizeQuery(queryText)
  const rel = relevanceFor(entry, terms, subQuestions || [], queryText, researchKind, undefined, question, undefined)
  return rel.score
}

export function screenCorpus(workspace: string, opts: CorpusScreenOptions, outputDir?: string): string {
  const entries = loadCorpus(workspace, outputDir)
  if (entries.length === 0) return 'Corpus is empty. Build corpus before screening.'
  // Fold the executed (English) search queries into the vocabulary for GENERAL research so
  // screening is robust when the user question language differs from the source language.
  // Academic screening is intentionally left untouched.
  const augment = String(opts.researchKind || 'academic') === 'general' && Array.isArray(opts.queryAugment)
    ? opts.queryAugment.filter((s) => typeof s === 'string' && s.trim())
    : []
  const queryText = [opts.question, ...(opts.subQuestions || []), ...augment].join(' ')
  const terms = tokenizeQuery(queryText)
  // Language-agnostic relevance: use the LLM-judged score cached for THIS exact query, if any.
  const currentQueryKey = semanticQueryKey(opts.question, opts.subQuestions)
  const semanticFor = (entry: CorpusEntry): number | undefined =>
    entry.semanticQueryKey === currentQueryKey && typeof entry.semanticRelevanceScore === 'number'
      ? entry.semanticRelevanceScore
      : undefined
  // LLM-assigned plan coverage for THIS query (language-agnostic). Primary sub-topic signal.
  const semanticSubQFor = (entry: CorpusEntry): string[] | undefined =>
    entry.semanticQueryKey === currentQueryKey && Array.isArray(entry.semanticSubQuestions)
      ? entry.semanticSubQuestions
      : undefined
  const minSelected = opts.minSelected && opts.minSelected > 0 ? Math.min(200, Math.trunc(opts.minSelected)) : 0
  // The requested floor must be able to raise the cap: if the user asked for ≥50 but
  // max_selected defaulted to 30, the cap would otherwise silently limit selection.
  const maxSelected = Math.max(Math.max(1, Math.min(200, Number(opts.maxSelected) || 30)), minSelected)
  const screened = entries.map((entry) => {
    const rel = relevanceFor(entry, terms, opts.subQuestions || [], queryText, opts.researchKind, semanticFor(entry), opts.question, semanticSubQFor(entry))
    const recency = recencyFor(entry, opts.yearFrom, opts.yearTo)
    const publicationType = classifyPublicationType(entry)
    const withType = { ...entry, publicationType }
    const authority = authorityFor(withType)
    const outsideDate = Boolean(opts.strictDateRange && outsideRequestedWindow(entry, opts))
    // Under a STRICT day-precise window a source WITHOUT a real day date cannot be confirmed
    // in-range — a bare year (2026) says nothing about whether it falls in Apr–Jul. Such a
    // source must never auto-select; we demote it to needs_review instead of rejecting
    // ("resolve then demote"): resolve its exact date (OpenAlex/arXiv/DOI) and it can count.
    // (Entries whose KNOWN year is already outside the window are rejected via outsideDate above.)
    const undatedUnderStrictWindow = Boolean(opts.strictDateRange && hasDayWindow(opts) && !entryIsoDate(entry))
    const windowLabel = hasDayWindow(opts)
      ? `${opts.fromDate ?? '*'}..${opts.toDate ?? '*'}`
      : `${opts.yearFrom ?? '*'}-${opts.yearTo ?? '*'}`
    const lowPrecision = rel.topicalPrecision < 50 || rel.blockers.length > 0
    // Recency is weighted higher (0.30) so genuinely new primary papers are not
    // crowded out by older high-authority surveys when the user wants the latest work.
    // sourcePreference nudges the academic pipeline toward open, dated indexes (arXiv/OpenAlex)
    // and away from closed, undated publisher landing pages (Springer/Elsevier/…).
    const selectedScore = rel.score * 0.5 + recency * 0.3 + authority * 0.2 + sourcePreferenceDelta(entry, opts.researchKind)
    const rejected = outsideDate || rel.score < 18 || rel.topicalPrecision < 30
    const updated: CorpusEntry = {
      ...entry,
      publicationType,
      relevanceScore: Math.round(rel.score),
      recencyScore: Math.round(recency),
      authorityScore: Math.round(authority),
      topicalPrecisionScore: Math.round(rel.topicalPrecision),
      subQuestions: rel.subQs.length ? rel.subQs : entry.subQuestions ?? [],
      screeningStatus: rejected ? 'rejected' : (undatedUnderStrictWindow || lowPrecision) ? 'needs_review' : selectedScore >= 42 ? 'selected' : 'needs_review',
      screeningReason: outsideDate
        ? `Outside strict date range ${windowLabel}`
        : rel.blockers.length
          ? `${rel.blockers.join('; ')}; matched: ${rel.matched.join(', ') || 'none'}`
        : rel.score < 18
          ? `Low topic relevance; matched: ${rel.matched.join(', ') || 'none'}`
        : undatedUnderStrictWindow
          ? `No day-precise date${entry.year ? ` (only year ${entry.year})` : ''} — cannot confirm within strict window ${windowLabel}; kept for review, not auto-selected. Resolve its exact date (OpenAlex/arXiv/DOI) to include it.`
          : `Selected score ${Math.round(selectedScore)}; precision ${Math.round(rel.topicalPrecision)}; type=${publicationType}; citations=${entry.citationCount ?? 'unknown'}; matched: ${rel.matched.slice(0, 8).join(', ') || 'semantic/context'}`,
      readPriority: selectedScore >= 62 && rel.topicalPrecision >= 60 ? 'high' : selectedScore >= 44 ? 'medium' : 'low',
      readStatus: entry.readStatus ?? (entry.status === 'read' ? 'read' : 'not_read'),
      updatedAt: Date.now(),
    }
    // Honor explicit human/agent decisions: a pinned rejection must NOT be resurrected by
    // re-screening, and a pinned selection must NOT be dropped. Without this, the agent's
    // own reject_corpus_items calls were undone by the next build_corpus/screen_corpus.
    if (entry.pinnedStatus === 'rejected') {
      updated.screeningStatus = 'rejected'
      updated.status = 'rejected'
      updated.readPriority = 'low'
      if (!/pinned/i.test(updated.screeningReason ?? '')) {
        updated.screeningReason = `Pinned as rejected (manual). ${updated.screeningReason ?? ''}`.trim()
      }
    } else if (entry.pinnedStatus === 'selected') {
      updated.screeningStatus = 'selected'
      if (!/pinned/i.test(updated.screeningReason ?? '')) {
        updated.screeningReason = `Pinned as selected (manual). ${updated.screeningReason ?? ''}`.trim()
      }
    }
    updated.score = scoreEntry(updated)
    return updated
  }).sort((a, b) => (b.score - a.score) || ((b.year ?? 0) - (a.year ?? 0)))

  // ---- Balanced selection under the cap -------------------------------------
  // A naive "top N by global score" cutoff lets a high-volume sub-topic (e.g. RLHF/LLM,
  // multi-agent RL — many highly-cited papers) consume every slot and starve sparser plan
  // items (general RL surveys, quantum RL) down to zero, even though on-topic surveys for
  // them ARE in the corpus. Guarantee each plan sub-question a small floor of slots first,
  // then fill the remainder by global score. `screened` is already sorted best-first.
  const planSubIds = (opts.subQuestions || []).map((_, i) => `Q${i + 1}`)
  const perTopicFloor = planSubIds.length
    ? Math.max(1, Math.min(3, Math.floor(maxSelected / planSubIds.length)))
    : 0
  const isSelectableEntry = (e: CorpusEntry) =>
    e.screeningStatus === 'selected'
    || (e.screeningStatus === 'needs_review'
      && (e.topicalPrecisionScore ?? 0) >= MIN_SELECTABLE_TOPICAL_PRECISION
      && (e.relevanceScore ?? 0) >= 18
      && !/^No day-precise date/.test(e.screeningReason ?? ''))
  const pool = screened.filter(isSelectableEntry)
  const covers = (e: CorpusEntry, q: string) => (e.subQuestions ?? []).includes(q)
  // A low max_selected — often the MODEL's arbitrary guess (e.g. 17) — must not discard
  // genuinely strong, clearly on-topic SURVEY/REVIEW sources that cover a plan sub-topic.
  // That is the recurring "good papers were left out" complaint. Expand the effective cap to
  // admit such strong items, bounded by a hard ceiling so reading effort stays sane.
  const STRONG_SELECT_CEILING = 40
  const isStrongSurvey = (e: CorpusEntry) =>
    (e.topicalPrecisionScore ?? 0) >= 70
    && (e.publicationType === 'survey' || e.publicationType === 'review' || (e.relevanceScore ?? 0) >= 60)
    && (e.subQuestions ?? []).length > 0
    // Don't spend EXPANDED slots on sources we probably can't read (paywalled publisher landing
    // pages, blogs). Half of an over-expanded selection was failing full-text read and showing
    // as "unavailable"; keep the expansion to open, retrievable surveys (arXiv/OA).
    && !likelyUnreadable(e)
  // A source the LLM judged highly on-topic (language-agnostic) must not be stranded in
  // needs_review just because it is a closed-publisher/DOI hit (isStrongSurvey excludes those as
  // "likely unreadable"). That stranding was the root of a run doing 61 searches and never
  // converging: excellent reasoning surveys (sem 85–95) sat unselected, coverage gates stayed
  // <100, and the agent kept searching instead of using what it already had. OA resolution
  // (OpenAlex best_oa_location) now makes many DOI hits readable, so admit them by semantic score
  // alone. Ceiling still bounds total reading effort.
  // No plan-subtopic requirement here: a high LLM relevance score already means "on-topic for the
  // research question". Requiring subQuestion coverage on top of it strands items whenever the plan
  // has no sub-questions or the lexical sub-topic matcher missed (cross-language) — which is exactly
  // how the excellent surveys got stuck in needs_review.
  const HIGH_SEMANTIC_SELECT = 75
  const isHighSemanticSurvey = (e: CorpusEntry) => (semanticFor(e) ?? -1) >= HIGH_SEMANTIC_SELECT
  const isExpandable = (e: CorpusEntry) => isStrongSurvey(e) || isHighSemanticSurvey(e)
  const strongCount = pool.filter(isExpandable).length
  const effectiveMax = Math.min(STRONG_SELECT_CEILING, Math.max(maxSelected, Math.min(strongCount, STRONG_SELECT_CEILING)))
  const keep = new Set<string>()
  // Manually pinned selections always survive the cap.
  for (const e of screened) if (e.pinnedStatus === 'selected' && e.screeningStatus === 'selected') keep.add(e.id)
  // Phase 1: guarantee each plan sub-topic its floor of the best covering sources.
  for (const q of planSubIds) {
    if (keep.size >= effectiveMax) break
    let covered = pool.filter((e) => keep.has(e.id) && covers(e, q)).length
    for (const e of pool) {
      if (keep.size >= effectiveMax || covered >= perTopicFloor) break
      if (keep.has(e.id) || !covers(e, q)) continue
      keep.add(e.id)
      covered++
    }
  }
  // Phase 2: admit strong on-topic surveys (incl. LLM-judged high-semantic hits), then fill
  // remaining slots by global score. `pool` is best-first, so the highest-scoring surveys win
  // the expanded slots.
  for (const e of pool) {
    if (keep.size >= effectiveMax) break
    if (isExpandable(e) && !keep.has(e.id)) keep.add(e.id)
  }
  for (const e of pool) {
    if (keep.size >= effectiveMax) break
    if (e.screeningStatus === 'selected' && !keep.has(e.id)) keep.add(e.id)
  }
  // Apply decisions: promote kept needs_review items, demote selected items that lost the cap.
  for (const entry of screened) {
    if (entry.pinnedStatus === 'selected') continue
    if (keep.has(entry.id)) {
      if (entry.screeningStatus !== 'selected') {
        entry.screeningStatus = 'selected'
        if (entry.readPriority === 'low') entry.readPriority = 'medium'
        entry.screeningReason = `Selected for plan coverage (${(entry.subQuestions ?? []).join(',') || 'general'}). ${entry.screeningReason ?? ''}`.trim()
        entry.score = scoreEntry(entry)
      }
    } else if (entry.screeningStatus === 'selected') {
      entry.screeningStatus = 'needs_review'
      entry.screeningReason = `Below top ${effectiveMax} selected cutoff. ${entry.screeningReason ?? ''}`.trim()
      entry.readPriority = 'low'
      entry.score = scoreEntry(entry)
    }
  }
  let selectedCount = keep.size
  // Soft floor: if the user asked for a minimum, promote the best ON-TOPIC
  // needs_review items (never rejected/off-topic) up to that floor. We never inject
  // off-topic noise just to hit a number — if there genuinely aren't enough on-topic
  // sources, selection stays short and the gap is visible.
  if (minSelected > selectedCount) {
    for (const entry of screened) {
      if (selectedCount >= minSelected) break
      if (entry.screeningStatus !== 'needs_review') continue
      // Never re-promote a source demoted for lacking a day-precise date under a strict window —
      // that would silently re-admit exactly what "resolve then demote" is meant to keep out. Its
      // exact date must be resolved (OpenAlex/arXiv/DOI) before it can count toward the window.
      if (/^No day-precise date/.test(entry.screeningReason ?? '')) continue
      // Only promote items that will also satisfy the topical_precision gate — otherwise a
      // promoted-to-hit-the-count item is flagged by the gate and the run loops/downgrades.
      const onTopic = (entry.topicalPrecisionScore ?? 0) >= MIN_SELECTABLE_TOPICAL_PRECISION && (entry.relevanceScore ?? 0) >= 18
      if (!onTopic) continue
      entry.screeningStatus = 'selected'
      if (entry.readPriority === 'low') entry.readPriority = 'medium'
      entry.screeningReason = `Promoted to meet minimum ${minSelected} selected (on-topic). ${entry.screeningReason ?? ''}`.trim()
      entry.score = scoreEntry(entry)
      selectedCount++
    }
  }
  saveCorpus(workspace, screened, outputDir)
  const stats = corpusStats(workspace, outputDir)
  return [
    `Screened ${screened.length} corpus item(s).`,
    `Selected: ${stats.selected}; needs review: ${stats.needsReview}; rejected: ${stats.rejected}.`,
    `Review/survey coverage: ${stats.selectedReviewLike}/${stats.selected} selected.`,
    '',
    listSelectedCorpus(workspace, 30, outputDir),
  ].join('\n')
}

export function listSelectedCorpus(workspace: string, max = 30, outputDir?: string): string {
  const entries = loadCorpus(workspace, outputDir)
    .filter((e) => e.screeningStatus === 'selected')
    .sort((a, b) => (b.score - a.score) || ((b.relevanceScore ?? 0) - (a.relevanceScore ?? 0)))
    .slice(0, Math.max(1, Math.min(100, max)))
  if (entries.length === 0) return 'No selected corpus items. Run screen_corpus first.'
  return entries.map((e, i) => [
    `${i + 1}. ${e.title}`,
    `   ID: ${e.id} | score=${e.score} | relevance=${e.relevanceScore ?? '-'} | priority=${e.readPriority ?? 'low'} | read=${e.readStatus ?? 'not_read'}`,
    `   Type: ${e.publicationType ?? 'unknown'} | precision=${e.topicalPrecisionScore ?? '-'} | citations=${e.citationCount ?? 'unknown'}`,
    e.subQuestions?.length ? `   Plan: ${e.subQuestions.join(', ')}` : null,
    e.year ? `   Year: ${e.year}` : null,
    `   URL: ${e.url}`,
    e.screeningReason ? `   Reason: ${e.screeningReason}` : null,
  ].filter(Boolean).join('\n')).join('\n\n')
}

/**
 * Structured list of currently-selected sources for the non-blocking review panel.
 * Sorted best-first so the most relevant sources are at the top of the checklist.
 */
export function getCorpusSelection(workspace: string, outputDir?: string, max = 80): CorpusSelectionItem[] {
  return loadCorpus(workspace, outputDir)
    .filter((e) => e.screeningStatus === 'selected')
    .sort((a, b) => (b.score - a.score) || ((b.relevanceScore ?? 0) - (a.relevanceScore ?? 0)))
    .slice(0, Math.max(1, Math.min(200, max)))
    .map((e) => ({
      id: e.id,
      title: e.title,
      year: e.year,
      url: e.url,
      publicationType: e.publicationType,
      subQuestions: e.subQuestions,
      included: true,
    }))
}

/**
 * Toggle a single source in/out of the selected set without losing read progress.
 * Used by the non-blocking "review selected sources" panel: the user can prune or
 * restore sources while the run keeps going. Excluding only flips screeningStatus to
 * 'rejected' (it does NOT mark readStatus=failed) so it is cleanly reversible.
 */
export function setCorpusItemIncluded(
  workspace: string,
  id: string,
  included: boolean,
  outputDir?: string,
): { ok: boolean; selected: number } {
  const entries = loadCorpus(workspace, outputDir)
  const entry = entries.find((e) => e.id === id)
  const selectedCount = () => entries.filter((e) => e.screeningStatus === 'selected').length
  if (!entry) return { ok: false, selected: selectedCount() }
  if (included) {
    entry.screeningStatus = 'selected'
    entry.pinnedStatus = 'selected'
    if (entry.status === 'rejected') entry.status = 'candidate'
    entry.screeningReason = 'Re-included by user'
  } else {
    entry.screeningStatus = 'rejected'
    entry.pinnedStatus = 'rejected'
    entry.status = 'rejected'
    entry.screeningReason = 'Excluded by user'
  }
  entry.updatedAt = Date.now()
  entry.score = scoreEntry(entry)
  saveCorpus(workspace, entries, outputDir)
  return { ok: true, selected: selectedCount() }
}

export function rejectCorpusItems(workspace: string, idsRaw: string, reason = 'Rejected by user/tool', outputDir?: string): string {
  const ids = new Set(String(idsRaw || '').split(/[,\s]+/).map((s) => s.trim()).filter(Boolean))
  if (ids.size === 0) return 'Error: provide one or more corpus IDs.'
  const entries = loadCorpus(workspace, outputDir)
  let changed = 0
  for (const e of entries) {
    if (ids.has(e.id)) {
      e.screeningStatus = 'rejected'
      e.pinnedStatus = 'rejected'
      e.status = 'rejected'
      e.readStatus = 'failed'
      e.screeningReason = reason
      e.updatedAt = Date.now()
      e.score = scoreEntry(e)
      changed++
    }
  }
  saveCorpus(workspace, entries, outputDir)
  return `Rejected ${changed} corpus item(s). They are pinned and will not be re-selected by future screening.`
}

export function assignCorpusToPlan(workspace: string, idsRaw: string, planItemId: string, outputDir?: string): string {
  const ids = new Set(String(idsRaw || '').split(/[,\s]+/).map((s) => s.trim()).filter(Boolean))
  const planId = String(planItemId || '').trim()
  if (ids.size === 0 || !planId) return 'Error: ids and plan_item_id are required.'
  const entries = loadCorpus(workspace, outputDir)
  let changed = 0
  for (const e of entries) {
    if (ids.has(e.id)) {
      e.subQuestions = [...new Set([...(e.subQuestions || []), planId])]
      // Deliberately routing a source to a plan item is an explicit re-inclusion, so a
      // prior rejection pin must be cleared (otherwise screening would revert it).
      if (e.screeningStatus === 'rejected' || e.pinnedStatus === 'rejected') e.pinnedStatus = undefined
      e.screeningStatus = e.screeningStatus === 'rejected' ? 'needs_review' : 'selected'
      e.updatedAt = Date.now()
      e.score = scoreEntry(e)
      changed++
    }
  }
  saveCorpus(workspace, entries, outputDir)
  return `Assigned ${changed} corpus item(s) to ${planId}.`
}

export function selectFullTextBatch(workspace: string, limit = 12, outputDir?: string): CorpusEntry[] {
  return loadCorpus(workspace, outputDir)
    .filter((e) => e.screeningStatus === 'selected' && e.readStatus !== 'read' && e.readStatus !== 'failed')
    .sort((a, b) => {
      const prio = (x: CorpusEntry) => x.readPriority === 'high' ? 3 : x.readPriority === 'medium' ? 2 : 1
      return prio(b) - prio(a) || b.score - a.score
    })
    .slice(0, Math.max(1, Math.min(50, Number(limit) || 12)))
}

export function markCorpusItemRead(workspace: string, id: string, localPath: string | undefined, readStatus: 'read' | 'failed', reason?: string, outputDir?: string): CorpusEntry | null {
  const entries = loadCorpus(workspace, outputDir)
  const entry = entries.find((e) => e.id === id)
  if (!entry) return null
  entry.readStatus = readStatus
  entry.status = readStatus === 'read' ? 'read' : entry.status
  entry.localPath = localPath ?? entry.localPath
  entry.readReason = reason
  entry.readAt = Date.now()
  entry.updatedAt = Date.now()
  entry.score = scoreEntry(entry)
  saveCorpus(workspace, entries, outputDir)
  return entry
}

export function fullTextStatus(workspace: string, outputDir?: string): string {
  const entries = loadCorpus(workspace, outputDir).filter((e) => e.screeningStatus === 'selected')
  if (entries.length === 0) return 'No selected corpus items. Run screen_corpus first.'
  const read = entries.filter((e) => e.readStatus === 'read').length
  const failed = entries.filter((e) => e.readStatus === 'failed').length
  const high = entries.filter((e) => e.readPriority === 'high')
  const highRead = high.filter((e) => e.readStatus === 'read').length
  const lines = [
    `Full-text status: ${read}/${entries.length} selected read; ${failed} failed; high-priority ${highRead}/${high.length} read.`,
    '',
  ]
  for (const e of entries.slice(0, 40)) {
    lines.push(`- ${e.id} [${e.readPriority ?? 'low'} / ${e.readStatus ?? 'not_read'}] ${e.title}${e.localPath ? ` -> ${e.localPath}` : ''}${e.readReason ? ` (${e.readReason})` : ''}`)
  }
  return lines.join('\n')
}
