import * as fs from 'fs'
import * as path from 'path'
import * as crypto from 'crypto'
import type { Source } from './sources'
import type { CorpusSelectionItem } from './types'
import { resolveResearchDir } from '../research-paths'

export interface CorpusEntry {
  id: string
  title: string
  url: string
  doi?: string
  arxivId?: string
  pmid?: string
  authors?: string
  year?: number
  date?: string
  sourceTool?: string
  snippet?: string
  venue?: string
  citationCount?: number
  publicationType?: 'survey' | 'review' | 'benchmark' | 'method' | 'tool' | 'safety' | 'background' | 'unknown'
  tier: 'primary' | 'secondary' | 'background'
  screeningStatus?: 'raw' | 'selected' | 'rejected' | 'needs_review'
  /**
   * A screening decision explicitly pinned by a human (review panel) or the agent
   * (reject_corpus_items). screen_corpus/build_corpus MUST respect it and never resurrect
   * a manually rejected source nor silently drop a manually kept one. This is the fix for
   * the "reject → rebuild → screen → off-topic comes back" loop that forced the
   * topical_precision gate to be downgraded and let off-topic papers into the report.
   */
  pinnedStatus?: 'selected' | 'rejected'
  screeningReason?: string
  relevanceScore?: number
  recencyScore?: number
  authorityScore?: number
  topicalPrecisionScore?: number
  readPriority?: 'high' | 'medium' | 'low'
  subQuestions?: string[]
  readStatus?: 'not_read' | 'queued' | 'read' | 'failed'
  readAt?: number
  readReason?: string
  status: 'candidate' | 'queued_full_text' | 'read' | 'rejected'
  score: number
  tags: string[]
  localPath?: string
  /** Cached per-source summary used in the report (generated by the LLM). */
  summary?: string
  /** Language of the cached summary ('ru' | 'en') so we can regenerate on language change. */
  summaryLang?: string
  addedAt: number
  updatedAt: number
}

export interface CorpusStats {
  total: number
  primary: number
  selected: number
  rejected: number
  needsReview: number
  queuedFullText: number
  read: number
  failed: number
  withDoi: number
  withArxiv: number
  selectedRead: number
  highPriority: number
  highPriorityRead: number
  reviewLike: number
  selectedReviewLike: number
  highCitation: number
}

export interface CorpusScreenOptions {
  question: string
  subQuestions?: string[]
  yearFrom?: number
  yearTo?: number
  maxSelected?: number
  /** Soft floor: promote the best on-topic items to reach this many selected. */
  minSelected?: number
  strictDateRange?: boolean
  /**
   * Topical-relevance strategy. 'academic' (default) keeps the ML/RL-aware precision
   * heuristic tuned for the science pipeline. 'general' (web research) judges relevance
   * generically from how well the source title/snippet covers the query terms, so the
   * gate actually filters off-topic pages for non-academic / non-ML topics.
   */
  researchKind?: 'general' | 'academic' | string
}

/**
 * Minimum topical-precision score for a source to be eligible for the `selected` set.
 * The floor-promotion in screenCorpus and the `topical_precision` quality gate share this
 * single threshold, so a source promoted to hit the minimum count can never afterwards be
 * flagged (and force-downgraded) by the gate. Keeping them in sync is what makes the
 * topical_precision gate genuinely passable by re-screening instead of only via downgrade.
 */
export const MIN_SELECTABLE_TOPICAL_PRECISION = 45

function researchDir(workspace: string, outputDir?: string): string {
  return resolveResearchDir(workspace, outputDir)
}

export function corpusPath(workspace: string, outputDir?: string): string {
  return path.join(researchDir(workspace, outputDir), 'corpus.jsonl')
}

function normalizeTitle(title: string): string {
  return title.toLowerCase().replace(/[^a-z0-9а-яё]+/gi, ' ').trim().replace(/\s+/g, ' ')
}

function slugHash(input: string): string {
  return crypto.createHash('sha1').update(input).digest('hex').slice(0, 10)
}

export function extractDoi(text: string): string | undefined {
  const doi = text.match(/\b10\.\d{4,9}\/[-._;()/:A-Z0-9]+/i)?.[0]
  return doi ? doi.replace(/[.,;)\]]+$/, '') : undefined
}

export function extractArxivId(text: string): string | undefined {
  const url = text.match(/arxiv\.org\/(?:abs|pdf|html)\/([^?\s#]+)/i)?.[1]
  if (url) return url.replace(/\.pdf$/i, '')
  const explicit = text.match(/\barxiv\s*:\s*([a-z-]+\/\d{7}(?:v\d+)?|\d{4}\.\d{4,5}(?:v\d+)?)\b/i)?.[1]
  if (explicit) return explicit
  const doiArxiv = text.match(/\b10\.48550\/arxiv\.([a-z-]+\/\d{7}(?:v\d+)?|\d{4}\.\d{4,5}(?:v\d+)?)\b/i)?.[1]
  return doiArxiv
}

export function extractPmid(text: string): string | undefined {
  return text.match(/\bPMID[:\s]+(\d{5,12})\b/i)?.[1] ?? text.match(/pubmed\.ncbi\.nlm\.nih\.gov\/(\d+)/i)?.[1]
}

function keyFor(entry: Pick<CorpusEntry, 'doi' | 'arxivId' | 'pmid' | 'url' | 'title'>): string {
  if (entry.doi) return `doi:${entry.doi.toLowerCase()}`
  if (entry.arxivId) return `arxiv:${entry.arxivId.toLowerCase().replace(/v\d+$/, '')}`
  if (entry.pmid) return `pmid:${entry.pmid}`
  if (entry.url) return `url:${entry.url.toLowerCase().replace(/\/$/, '')}`
  return `title:${normalizeTitle(entry.title)}`
}

export function loadCorpus(workspace: string, outputDir?: string): CorpusEntry[] {
  const p = corpusPath(workspace, outputDir)
  if (!fs.existsSync(p)) return []
  try {
    return fs.readFileSync(p, 'utf-8')
      .split('\n')
      .filter(Boolean)
      .map((line) => normalizeEntry(JSON.parse(line) as CorpusEntry))
  } catch { return [] }
}

function normalizeEntry(entry: CorpusEntry): CorpusEntry {
  const readStatus = entry.readStatus
    ?? (entry.status === 'read' ? 'read' : entry.status === 'queued_full_text' ? 'queued' : entry.status === 'rejected' ? 'failed' : 'not_read')
  const screeningStatus = entry.screeningStatus ?? (entry.status === 'rejected' ? 'rejected' : 'raw')
  return {
    ...entry,
    publicationType: entry.publicationType ?? classifyPublicationType(entry),
    screeningStatus,
    readStatus,
    subQuestions: Array.isArray(entry.subQuestions) ? entry.subQuestions : [],
  }
}

export function saveCorpus(workspace: string, entries: CorpusEntry[], outputDir?: string): void {
  const p = corpusPath(workspace, outputDir)
  fs.mkdirSync(path.dirname(p), { recursive: true })
  const sorted = [...entries].sort((a, b) => b.score - a.score || b.updatedAt - a.updatedAt)
  fs.writeFileSync(p, sorted.map((e) => JSON.stringify(e)).join('\n') + (sorted.length ? '\n' : ''), 'utf-8')
}

function scoreEntry(entry: CorpusEntry): number {
  let score = 10
  if (entry.doi) score += 15
  if (entry.arxivId) score += 12
  if (entry.pmid) score += 12
  if (entry.url.includes('arxiv.org') || entry.url.includes('doi.org') || entry.url.includes('pubmed')) score += 8
  if ((entry.citationCount ?? 0) >= 50) score += 8
  if ((entry.citationCount ?? 0) >= 200) score += 8
  if (entry.publicationType === 'survey' || entry.publicationType === 'review') score += 12
  if ((entry.topicalPrecisionScore ?? 0) < 35) score -= 20
  if (entry.snippet && entry.snippet.length > 80) score += 5
  if (entry.year && entry.year >= new Date().getFullYear() - 1) score += 6
  if (entry.tier === 'primary') score += 10
  score += Math.round(entry.relevanceScore ?? 0)
  score += Math.round((entry.authorityScore ?? 0) / 2)
  score += Math.round((entry.recencyScore ?? 0) / 2)
  if (entry.screeningStatus === 'selected') score += 20
  if (entry.readPriority === 'high') score += 8
  if (entry.screeningStatus === 'rejected') score -= 100
  return score
}

export function sourceToCorpusEntry(source: Source | Omit<Source, 'idx'>, tags: string[] = []): CorpusEntry {
  const now = Date.now()
  const text = `${source.title}\n${source.url}\n${source.snippet ?? ''}`
  const doi = extractDoi(text)
  const arxivId = extractArxivId(text)
  const pmid = extractPmid(text)
  const venue = extractLineValue(text, 'Venue')
  const citationCount = extractNumberLineValue(text, 'Citations')
  const year = Number(String(source.date ?? '').match(/\b(19|20)\d{2}\b/)?.[0]) || undefined
  const tier: CorpusEntry['tier'] = source.sourceTool?.includes('web') ? 'secondary' : 'primary'
  const id = slugHash(keyFor({ title: source.title, url: source.url, doi, arxivId, pmid }))
  const entry: CorpusEntry = {
    id,
    title: source.title,
    url: source.url,
    doi,
    arxivId,
    pmid,
    authors: source.authors,
    venue,
    citationCount,
    year,
    date: source.date,
    sourceTool: source.sourceTool,
    snippet: source.snippet,
    tier,
    publicationType: 'unknown',
    screeningStatus: 'raw',
    readStatus: 'not_read',
    subQuestions: [],
    status: 'candidate',
    score: 0,
    tags,
    addedAt: now,
    updatedAt: now,
  }
  entry.publicationType = classifyPublicationType(entry)
  entry.score = scoreEntry(entry)
  return entry
}

export function mergeCorpusEntries(existing: CorpusEntry[], incoming: CorpusEntry[]): { entries: CorpusEntry[]; added: number; updated: number } {
  const byKey = new Map<string, CorpusEntry>()
  for (const e of existing) byKey.set(keyFor(e), e)
  let added = 0
  let updated = 0
  for (const next of incoming) {
    const k = keyFor(next)
    const prev = byKey.get(k)
    if (!prev) {
      byKey.set(k, next)
      added++
    } else {
      // A freshly-built incoming entry carries default/raw progress (readStatus
      // 'not_read', screeningStatus 'raw', no localPath). Spreading it over `prev`
      // would wipe screening/read progress accumulated during the run — which made
      // a rebuild silently lose selections and reads, and left status='read' with
      // readStatus='not_read' (an inconsistency that loops the reader). Keep the
      // workflow-progress fields sticky so re-merges never regress them.
      const keepReadStatus =
        prev.readStatus === 'read' || prev.readStatus === 'failed' || prev.readStatus === 'queued'
          ? prev.readStatus
          : (next.readStatus ?? prev.readStatus)
      const keepScreening =
        prev.screeningStatus && prev.screeningStatus !== 'raw'
          ? prev.screeningStatus
          : (next.screeningStatus ?? prev.screeningStatus)
      byKey.set(k, {
        ...prev,
        ...Object.fromEntries(Object.entries(next).filter(([, v]) => v !== undefined && v !== '')),
        id: prev.id,
        tags: [...new Set([...(prev.tags || []), ...(next.tags || [])])],
        status: prev.status === 'read' ? 'read' : next.status,
        screeningStatus: keepScreening,
        readStatus: keepReadStatus,
        readPriority: prev.readPriority ?? next.readPriority,
        localPath: prev.localPath ?? next.localPath,
        readReason: prev.readReason ?? next.readReason,
        subQuestions: prev.subQuestions?.length ? prev.subQuestions : (next.subQuestions ?? []),
        score: Math.max(prev.score, next.score),
        addedAt: prev.addedAt,
        updatedAt: Date.now(),
      } as CorpusEntry)
      updated++
    }
  }
  return { entries: [...byKey.values()], added, updated }
}

export function addSourcesToCorpus(workspace: string, sources: Array<Source | Omit<Source, 'idx'>>, tags: string[] = [], outputDir?: string): { entries: CorpusEntry[]; added: number; updated: number } {
  const existing = loadCorpus(workspace, outputDir)
  const incoming = sources.filter((s) => s.title && s.url).map((s) => sourceToCorpusEntry(s, tags))
  const merged = mergeCorpusEntries(existing, incoming)
  saveCorpus(workspace, merged.entries, outputDir)
  return merged
}

export function corpusStats(workspace: string, outputDir?: string): CorpusStats {
  const entries = loadCorpus(workspace, outputDir)
  const selected = entries.filter((e) => e.screeningStatus === 'selected')
  const highPriority = entries.filter((e) => e.screeningStatus === 'selected' && e.readPriority === 'high')
  return {
    total: entries.length,
    primary: entries.filter((e) => e.tier === 'primary').length,
    selected: selected.length,
    rejected: entries.filter((e) => e.screeningStatus === 'rejected').length,
    needsReview: entries.filter((e) => e.screeningStatus === 'needs_review').length,
    queuedFullText: entries.filter((e) => e.readStatus === 'queued' || e.status === 'queued_full_text').length,
    read: entries.filter((e) => e.readStatus === 'read' || e.status === 'read').length,
    failed: entries.filter((e) => e.readStatus === 'failed').length,
    withDoi: entries.filter((e) => !!e.doi).length,
    withArxiv: entries.filter((e) => !!e.arxivId).length,
    selectedRead: selected.filter((e) => e.readStatus === 'read' || e.status === 'read').length,
    highPriority: highPriority.length,
    highPriorityRead: highPriority.filter((e) => e.readStatus === 'read' || e.status === 'read').length,
    reviewLike: entries.filter(isReviewLike).length,
    selectedReviewLike: selected.filter(isReviewLike).length,
    highCitation: entries.filter((e) => (e.citationCount ?? 0) >= 50).length,
  }
}

export function listCorpus(workspace: string, max = 20, outputDir?: string): string {
  const entries = loadCorpus(workspace, outputDir).slice(0, Math.max(1, Math.min(100, max)))
  if (entries.length === 0) return 'Corpus is empty. Use build_corpus or add_to_corpus after search.'
  const stats = corpusStats(workspace, outputDir)
  const lines = [`Corpus: ${stats.total} items (${stats.primary} primary, ${stats.queuedFullText} queued full text, ${stats.read} read)\n`]
  entries.forEach((e, i) => {
    lines.push([
      `${i + 1}. ${e.title}`,
      `   ID: ${e.id} | score=${e.score} | ${e.tier} | screen=${e.screeningStatus ?? 'raw'} | read=${e.readStatus ?? e.status}`,
      e.year ? `   Year: ${e.year}` : null,
      e.doi ? `   DOI: ${e.doi}` : null,
      e.arxivId ? `   arXiv: ${e.arxivId}` : null,
      e.citationCount !== undefined ? `   Citations: ${e.citationCount}` : null,
      e.publicationType ? `   Type: ${e.publicationType}` : null,
      `   URL: ${e.url}`,
      e.snippet ? `   Snippet: ${e.snippet.slice(0, 220)}` : null,
    ].filter(Boolean).join('\n'))
  })
  return lines.join('\n\n')
}

export function queueFullText(workspace: string, ids?: string[], outputDir?: string): string {
  const entries = loadCorpus(workspace, outputDir)
  const wanted = new Set((ids || []).map(String))
  let changed = 0
  for (const e of entries) {
    if (wanted.size === 0 || wanted.has(e.id)) {
      if (e.status === 'candidate') {
        e.status = 'queued_full_text'
        e.readStatus = 'queued'
        e.updatedAt = Date.now()
        changed++
      }
    }
  }
  saveCorpus(workspace, entries, outputDir)
  return `Queued ${changed} corpus item(s) for full-text reading.`
}

export function rankCorpus(workspace: string, outputDir?: string): string {
  const entries = loadCorpus(workspace, outputDir).map((e) => ({ ...e, score: scoreEntry(e), updatedAt: Date.now() }))
  saveCorpus(workspace, entries, outputDir)
  return listCorpus(workspace, 30, outputDir)
}

function tokenizeQuery(text: string): string[] {
  const stop = new Set(['the', 'and', 'for', 'with', 'from', 'into', 'about', 'какие', 'какой', 'как', 'что', 'для', 'или', 'это', 'over', 'last'])
  return String(text || '').toLowerCase()
    .replace(/[^a-z0-9а-яё+.-]+/gi, ' ')
    .split(/\s+/)
    .map((t) => t.trim())
    .filter((t) => t.length >= 3 && !stop.has(t))
}

function extractLineValue(text: string, label: string): string | undefined {
  return text.match(new RegExp(`^\\s*${label}:\\s*(.+)$`, 'im'))?.[1]?.trim()
}

function extractNumberLineValue(text: string, label: string): number | undefined {
  const value = extractLineValue(text, label)
  if (!value) return undefined
  const n = Number(value.replace(/[^\d.-]+/g, ''))
  return Number.isFinite(n) ? n : undefined
}

function classifyPublicationType(entry: Pick<CorpusEntry, 'title' | 'snippet' | 'venue' | 'url'>): CorpusEntry['publicationType'] {
  const text = `${entry.title} ${entry.snippet ?? ''} ${entry.venue ?? ''} ${entry.url ?? ''}`.toLowerCase()
  if (/\b(systematic\s+review|meta[- ]analysis|survey|review|overview|state[- ]of[- ]the[- ]art)\b/i.test(text)) return /survey/i.test(text) ? 'survey' : 'review'
  if (/\bbenchmark|leaderboard|evaluation suite|dataset\b/i.test(text)) return 'benchmark'
  if (/\bframework|library|toolkit|open-source|github|trl|openrlhf|verl|vllm\b/i.test(text)) return 'tool'
  if (/\bsafety|alignment|poison|bias|jailbreak|harm|robustness\b/i.test(text)) return 'safety'
  if (/\bmethod|approach|algorithm|training|optimization|fine[- ]tuning|post[- ]training\b/i.test(text)) return 'method'
  return 'unknown'
}

export function isReviewLike(entry: Pick<CorpusEntry, 'publicationType' | 'title' | 'snippet'>): boolean {
  return entry.publicationType === 'survey'
    || entry.publicationType === 'review'
    || /\b(survey|review|overview|systematic|meta[- ]analysis|state[- ]of[- ]the[- ]art)\b/i.test(`${entry.title} ${entry.snippet ?? ''}`)
}

/**
 * Generic topical precision for general (web) research. The ML/RL heuristic below
 * only understands LLM/RL vocabulary, so for any non-ML topic it returns a flat 50
 * and stops filtering. Here we judge relevance from how much of the query vocabulary
 * the source's own title/snippet actually covers — a source that shares none of the
 * query terms is off-topic and must be rejected, regardless of recency or authority.
 */
function genericTopicPrecisionFor(entry: CorpusEntry, queryText: string): { score: number; blockers: string[] } {
  const text = `${entry.title} ${entry.snippet ?? ''}`.toLowerCase()
  const terms = [...new Set(tokenizeQuery(queryText))]
  if (terms.length === 0) return { score: 60, blockers: [] }
  const hits = terms.filter((t) => text.includes(t)).length
  const coverage = hits / terms.length
  if (hits === 0) {
    return { score: 8, blockers: ['Off-topic: none of the query terms appear in the source title/snippet'] }
  }
  const score = Math.max(0, Math.min(100, Math.round(35 + coverage * 80)))
  return { score, blockers: [] }
}

function topicPrecisionFor(entry: CorpusEntry, queryText: string, researchKind?: string): { score: number; blockers: string[] } {
  // General (web) research is not RL/LLM-specific, so the academic heuristic would be a
  // no-op (flat 50) and let junk through. Use the generic query-coverage relevance instead.
  if (String(researchKind || 'academic') === 'general') return genericTopicPrecisionFor(entry, queryText)
  // IMPORTANT: do NOT include entry.tags here. `build_corpus` applies the same
  // query-level topic tags (e.g. "RL,LLM,RLHF,DPO,...") uniformly to every source,
  // so trusting tags would make every item look on-topic (precision=100) and fully
  // defeat this gate — letting astrophysics/quantum/math papers pass screening.
  // Topical precision must be judged from the source's own title + snippet only.
  const text = `${entry.title} ${entry.snippet ?? ''}`.toLowerCase()
  const query = queryText.toLowerCase()
  const wantsLlm = /\b(llm|large language model|language models?|chatgpt|reasoning model|post-training|post training)\b/i.test(query)
  const wantsRl = /\b(reinforcement learning|rlhf|rlvr|grpo|dpo|ppo|rloo|\brl\b|reward|policy optimization|preference optimization)\b/i.test(query)
  const hasLlm = /\b(llm|large language model|language models?|chatgpt|reasoning model|post-training|post training)\b/i.test(text)
  const hasRl = /\b(reinforcement learning|rlhf|rlvr|grpo|dpo|ppo|rloo|\brl\b|reward|policy optimization|preference optimization)\b/i.test(text)
  const blockers: string[] = []
  let score = 50
  if (wantsLlm) score += hasLlm ? 25 : -30
  if (wantsRl) score += hasRl ? 30 : -35
  if (wantsLlm && wantsRl && !(hasLlm && hasRl)) blockers.push('Missing required RL+LLM topical intersection')
  if (/\b(vulnerability|chemistry|speech synthesis|image restoration|constructional semantics|medical applications|gravitational waves)\b/i.test(text)) {
    score -= 30
    blockers.push('Likely off-topic for requested research scope')
  }
  return { score: Math.max(0, Math.min(100, score)), blockers }
}

function relevanceFor(entry: CorpusEntry, terms: string[], subQuestions: string[], queryText: string, researchKind?: string): { score: number; matched: string[]; subQs: string[]; topicalPrecision: number; blockers: string[] } {
  const text = `${entry.title} ${entry.snippet ?? ''} ${entry.authors ?? ''}`.toLowerCase()
  const matched = [...new Set(terms.filter((t) => text.includes(t)))]
  const rlBoost = ['reinforcement', 'learning', 'rl', 'rlhf', 'dpo', 'ppo', 'reward', 'policy', 'q-learning', 'offline', 'safe', 'robot', 'marl', 'agent', 'verifiable'].filter((t) => text.includes(t))
  const subQs = subQuestions
    .map((q, i) => ({ id: `Q${i + 1}`, hits: tokenizeQuery(q).filter((t) => text.includes(t)).length }))
    .filter((x) => x.hits > 0)
    .sort((a, b) => b.hits - a.hits)
    .slice(0, 3)
    .map((x) => x.id)
  const precision = topicPrecisionFor(entry, queryText, researchKind)
  return {
    score: Math.min(100, matched.length * 7 + rlBoost.length * 8 + subQs.length * 8 + Math.round(precision.score * 0.25)),
    matched,
    subQs,
    topicalPrecision: precision.score,
    blockers: precision.blockers,
  }
}

function recencyFor(entry: CorpusEntry, yearFrom?: number, yearTo?: number): number {
  if (!entry.year) return 20
  if (yearFrom && entry.year < yearFrom) return 0
  if (yearTo && entry.year > yearTo) return 20
  const current = new Date().getFullYear()
  return Math.max(15, Math.min(100, 100 - Math.max(0, current - entry.year) * 12))
}

function authorityFor(entry: CorpusEntry): number {
  let score = 20
  if (entry.doi) score += 20
  if (entry.arxivId) score += 20
  if ((entry.citationCount ?? 0) >= 25) score += 10
  if ((entry.citationCount ?? 0) >= 100) score += 10
  if (isReviewLike(entry)) score += 20
  if (/benchmark|nature|neurips|iclr|icml|acl|emnlp|naacl|science/i.test(`${entry.title} ${entry.snippet ?? ''} ${entry.venue ?? ''}`)) score += 20
  if (/openalex|semantic|crossref|pubmed|arxiv/i.test(entry.sourceTool ?? '')) score += 10
  return Math.min(100, score)
}

export function screenCorpus(workspace: string, opts: CorpusScreenOptions, outputDir?: string): string {
  const entries = loadCorpus(workspace, outputDir)
  if (entries.length === 0) return 'Corpus is empty. Build corpus before screening.'
  const queryText = [opts.question, ...(opts.subQuestions || [])].join(' ')
  const terms = tokenizeQuery(queryText)
  const minSelected = opts.minSelected && opts.minSelected > 0 ? Math.min(200, Math.trunc(opts.minSelected)) : 0
  // The requested floor must be able to raise the cap: if the user asked for ≥50 but
  // max_selected defaulted to 30, the cap would otherwise silently limit selection.
  const maxSelected = Math.max(Math.max(1, Math.min(200, Number(opts.maxSelected) || 30)), minSelected)
  const screened = entries.map((entry) => {
    const rel = relevanceFor(entry, terms, opts.subQuestions || [], queryText, opts.researchKind)
    const recency = recencyFor(entry, opts.yearFrom, opts.yearTo)
    const publicationType = classifyPublicationType(entry)
    const withType = { ...entry, publicationType }
    const authority = authorityFor(withType)
    const outsideDate = Boolean(opts.strictDateRange && entry.year && ((opts.yearFrom && entry.year < opts.yearFrom) || (opts.yearTo && entry.year > opts.yearTo)))
    const lowPrecision = rel.topicalPrecision < 50 || rel.blockers.length > 0
    // Recency is weighted higher (0.30) so genuinely new primary papers are not
    // crowded out by older high-authority surveys when the user wants the latest work.
    const selectedScore = rel.score * 0.5 + recency * 0.3 + authority * 0.2
    const updated: CorpusEntry = {
      ...entry,
      publicationType,
      relevanceScore: Math.round(rel.score),
      recencyScore: Math.round(recency),
      authorityScore: Math.round(authority),
      topicalPrecisionScore: Math.round(rel.topicalPrecision),
      subQuestions: rel.subQs.length ? rel.subQs : entry.subQuestions ?? [],
      screeningStatus: outsideDate || rel.score < 18 || rel.topicalPrecision < 30 ? 'rejected' : lowPrecision ? 'needs_review' : selectedScore >= 42 ? 'selected' : 'needs_review',
      screeningReason: outsideDate
        ? `Outside strict date range ${opts.yearFrom ?? '*'}-${opts.yearTo ?? '*'}`
        : rel.blockers.length
          ? `${rel.blockers.join('; ')}; matched: ${rel.matched.join(', ') || 'none'}`
        : rel.score < 18
          ? `Low topic relevance; matched: ${rel.matched.join(', ') || 'none'}`
          : `Selected score ${Math.round(selectedScore)}; precision ${Math.round(rel.topicalPrecision)}; type=${publicationType}; citations=${entry.citationCount ?? 'unknown'}; matched: ${rel.matched.slice(0, 8).join(', ') || 'semantic/context'}`,
      readPriority: selectedScore >= 62 && rel.topicalPrecision >= 60 ? 'high' : selectedScore >= 44 ? 'medium' : 'low',
      readStatus: entry.readStatus ?? (entry.status === 'read' ? 'read' : 'not_read'),
      updatedAt: Date.now(),
    }
    // Honor explicit human/agent decisions: a pinned rejection must NOT be resurrected by
    // re-screening, and a pinned selection must NOT be dropped. Without this, the agent's
    // own reject_corpus_items calls were undone by the next build_corpus/screen_corpus.
    if (entry.pinnedStatus === 'rejected') {
      updated.screeningStatus = 'rejected'
      updated.status = 'rejected'
      updated.readPriority = 'low'
      if (!/pinned/i.test(updated.screeningReason ?? '')) {
        updated.screeningReason = `Pinned as rejected (manual). ${updated.screeningReason ?? ''}`.trim()
      }
    } else if (entry.pinnedStatus === 'selected') {
      updated.screeningStatus = 'selected'
      if (!/pinned/i.test(updated.screeningReason ?? '')) {
        updated.screeningReason = `Pinned as selected (manual). ${updated.screeningReason ?? ''}`.trim()
      }
    }
    updated.score = scoreEntry(updated)
    return updated
  }).sort((a, b) => (b.score - a.score) || ((b.year ?? 0) - (a.year ?? 0)))

  let selectedCount = 0
  for (const entry of screened) {
    if (entry.screeningStatus === 'selected') {
      // Manually pinned selections always survive the cap.
      if (entry.pinnedStatus === 'selected') {
        selectedCount++
      } else if (selectedCount >= maxSelected) {
        entry.screeningStatus = 'needs_review'
        entry.screeningReason = `Below top ${maxSelected} selected cutoff. ${entry.screeningReason ?? ''}`.trim()
        entry.readPriority = 'low'
        entry.score = scoreEntry(entry)
      } else {
        selectedCount++
      }
    }
  }
  // Soft floor: if the user asked for a minimum, promote the best ON-TOPIC
  // needs_review items (never rejected/off-topic) up to that floor. We never inject
  // off-topic noise just to hit a number — if there genuinely aren't enough on-topic
  // sources, selection stays short and the gap is visible.
  if (minSelected > selectedCount) {
    for (const entry of screened) {
      if (selectedCount >= minSelected) break
      if (entry.screeningStatus !== 'needs_review') continue
      // Only promote items that will also satisfy the topical_precision gate — otherwise a
      // promoted-to-hit-the-count item is flagged by the gate and the run loops/downgrades.
      const onTopic = (entry.topicalPrecisionScore ?? 0) >= MIN_SELECTABLE_TOPICAL_PRECISION && (entry.relevanceScore ?? 0) >= 18
      if (!onTopic) continue
      entry.screeningStatus = 'selected'
      if (entry.readPriority === 'low') entry.readPriority = 'medium'
      entry.screeningReason = `Promoted to meet minimum ${minSelected} selected (on-topic). ${entry.screeningReason ?? ''}`.trim()
      entry.score = scoreEntry(entry)
      selectedCount++
    }
  }
  saveCorpus(workspace, screened, outputDir)
  const stats = corpusStats(workspace, outputDir)
  return [
    `Screened ${screened.length} corpus item(s).`,
    `Selected: ${stats.selected}; needs review: ${stats.needsReview}; rejected: ${stats.rejected}.`,
    `Review/survey coverage: ${stats.selectedReviewLike}/${stats.selected} selected.`,
    '',
    listSelectedCorpus(workspace, 30, outputDir),
  ].join('\n')
}

export function listSelectedCorpus(workspace: string, max = 30, outputDir?: string): string {
  const entries = loadCorpus(workspace, outputDir)
    .filter((e) => e.screeningStatus === 'selected')
    .sort((a, b) => (b.score - a.score) || ((b.relevanceScore ?? 0) - (a.relevanceScore ?? 0)))
    .slice(0, Math.max(1, Math.min(100, max)))
  if (entries.length === 0) return 'No selected corpus items. Run screen_corpus first.'
  return entries.map((e, i) => [
    `${i + 1}. ${e.title}`,
    `   ID: ${e.id} | score=${e.score} | relevance=${e.relevanceScore ?? '-'} | priority=${e.readPriority ?? 'low'} | read=${e.readStatus ?? 'not_read'}`,
    `   Type: ${e.publicationType ?? 'unknown'} | precision=${e.topicalPrecisionScore ?? '-'} | citations=${e.citationCount ?? 'unknown'}`,
    e.subQuestions?.length ? `   Plan: ${e.subQuestions.join(', ')}` : null,
    e.year ? `   Year: ${e.year}` : null,
    `   URL: ${e.url}`,
    e.screeningReason ? `   Reason: ${e.screeningReason}` : null,
  ].filter(Boolean).join('\n')).join('\n\n')
}

/**
 * Structured list of currently-selected sources for the non-blocking review panel.
 * Sorted best-first so the most relevant sources are at the top of the checklist.
 */
export function getCorpusSelection(workspace: string, outputDir?: string, max = 80): CorpusSelectionItem[] {
  return loadCorpus(workspace, outputDir)
    .filter((e) => e.screeningStatus === 'selected')
    .sort((a, b) => (b.score - a.score) || ((b.relevanceScore ?? 0) - (a.relevanceScore ?? 0)))
    .slice(0, Math.max(1, Math.min(200, max)))
    .map((e) => ({
      id: e.id,
      title: e.title,
      year: e.year,
      url: e.url,
      publicationType: e.publicationType,
      subQuestions: e.subQuestions,
      included: true,
    }))
}

/**
 * Toggle a single source in/out of the selected set without losing read progress.
 * Used by the non-blocking "review selected sources" panel: the user can prune or
 * restore sources while the run keeps going. Excluding only flips screeningStatus to
 * 'rejected' (it does NOT mark readStatus=failed) so it is cleanly reversible.
 */
export function setCorpusItemIncluded(
  workspace: string,
  id: string,
  included: boolean,
  outputDir?: string,
): { ok: boolean; selected: number } {
  const entries = loadCorpus(workspace, outputDir)
  const entry = entries.find((e) => e.id === id)
  const selectedCount = () => entries.filter((e) => e.screeningStatus === 'selected').length
  if (!entry) return { ok: false, selected: selectedCount() }
  if (included) {
    entry.screeningStatus = 'selected'
    entry.pinnedStatus = 'selected'
    if (entry.status === 'rejected') entry.status = 'candidate'
    entry.screeningReason = 'Re-included by user'
  } else {
    entry.screeningStatus = 'rejected'
    entry.pinnedStatus = 'rejected'
    entry.status = 'rejected'
    entry.screeningReason = 'Excluded by user'
  }
  entry.updatedAt = Date.now()
  entry.score = scoreEntry(entry)
  saveCorpus(workspace, entries, outputDir)
  return { ok: true, selected: selectedCount() }
}

export function rejectCorpusItems(workspace: string, idsRaw: string, reason = 'Rejected by user/tool', outputDir?: string): string {
  const ids = new Set(String(idsRaw || '').split(/[,\s]+/).map((s) => s.trim()).filter(Boolean))
  if (ids.size === 0) return 'Error: provide one or more corpus IDs.'
  const entries = loadCorpus(workspace, outputDir)
  let changed = 0
  for (const e of entries) {
    if (ids.has(e.id)) {
      e.screeningStatus = 'rejected'
      e.pinnedStatus = 'rejected'
      e.status = 'rejected'
      e.readStatus = 'failed'
      e.screeningReason = reason
      e.updatedAt = Date.now()
      e.score = scoreEntry(e)
      changed++
    }
  }
  saveCorpus(workspace, entries, outputDir)
  return `Rejected ${changed} corpus item(s). They are pinned and will not be re-selected by future screening.`
}

export function assignCorpusToPlan(workspace: string, idsRaw: string, planItemId: string, outputDir?: string): string {
  const ids = new Set(String(idsRaw || '').split(/[,\s]+/).map((s) => s.trim()).filter(Boolean))
  const planId = String(planItemId || '').trim()
  if (ids.size === 0 || !planId) return 'Error: ids and plan_item_id are required.'
  const entries = loadCorpus(workspace, outputDir)
  let changed = 0
  for (const e of entries) {
    if (ids.has(e.id)) {
      e.subQuestions = [...new Set([...(e.subQuestions || []), planId])]
      // Deliberately routing a source to a plan item is an explicit re-inclusion, so a
      // prior rejection pin must be cleared (otherwise screening would revert it).
      if (e.screeningStatus === 'rejected' || e.pinnedStatus === 'rejected') e.pinnedStatus = undefined
      e.screeningStatus = e.screeningStatus === 'rejected' ? 'needs_review' : 'selected'
      e.updatedAt = Date.now()
      e.score = scoreEntry(e)
      changed++
    }
  }
  saveCorpus(workspace, entries, outputDir)
  return `Assigned ${changed} corpus item(s) to ${planId}.`
}

export function selectFullTextBatch(workspace: string, limit = 12, outputDir?: string): CorpusEntry[] {
  return loadCorpus(workspace, outputDir)
    .filter((e) => e.screeningStatus === 'selected' && e.readStatus !== 'read' && e.readStatus !== 'failed')
    .sort((a, b) => {
      const prio = (x: CorpusEntry) => x.readPriority === 'high' ? 3 : x.readPriority === 'medium' ? 2 : 1
      return prio(b) - prio(a) || b.score - a.score
    })
    .slice(0, Math.max(1, Math.min(50, Number(limit) || 12)))
}

export function markCorpusItemRead(workspace: string, id: string, localPath: string | undefined, readStatus: 'read' | 'failed', reason?: string, outputDir?: string): CorpusEntry | null {
  const entries = loadCorpus(workspace, outputDir)
  const entry = entries.find((e) => e.id === id)
  if (!entry) return null
  entry.readStatus = readStatus
  entry.status = readStatus === 'read' ? 'read' : entry.status
  entry.localPath = localPath ?? entry.localPath
  entry.readReason = reason
  entry.readAt = Date.now()
  entry.updatedAt = Date.now()
  entry.score = scoreEntry(entry)
  saveCorpus(workspace, entries, outputDir)
  return entry
}

export function fullTextStatus(workspace: string, outputDir?: string): string {
  const entries = loadCorpus(workspace, outputDir).filter((e) => e.screeningStatus === 'selected')
  if (entries.length === 0) return 'No selected corpus items. Run screen_corpus first.'
  const read = entries.filter((e) => e.readStatus === 'read').length
  const failed = entries.filter((e) => e.readStatus === 'failed').length
  const high = entries.filter((e) => e.readPriority === 'high')
  const highRead = high.filter((e) => e.readStatus === 'read').length
  const lines = [
    `Full-text status: ${read}/${entries.length} selected read; ${failed} failed; high-priority ${highRead}/${high.length} read.`,
    '',
  ]
  for (const e of entries.slice(0, 40)) {
    lines.push(`- ${e.id} [${e.readPriority ?? 'low'} / ${e.readStatus ?? 'not_read'}] ${e.title}${e.localPath ? ` -> ${e.localPath}` : ''}${e.readReason ? ` (${e.readReason})` : ''}`)
  }
  return lines.join('\n')
}
