import * as fs from 'fs'
import * as path from 'path'

export interface PlanItem {
  id: string
  text: string
  done: boolean
  level: number
  children: PlanItem[]
}

export function planPath(workspacePath: string): string {
  return path.join(workspacePath, '.research', 'plan.md')
}

/**
 * Create or overwrite plan.md with a structured, checkable plan.
 */
export function writePlan(workspacePath: string, question: string, subQuestions: string[]): string {
  const p = planPath(workspacePath)
  fs.mkdirSync(path.dirname(p), { recursive: true })
  const lines: string[] = []
  lines.push(`# Research Plan: ${question}`)
  lines.push('')
  lines.push('_Autogenerated. Edit freely; the agent will read checkboxes to track progress._')
  lines.push('')
  for (let i = 0; i < subQuestions.length; i++) {
    const sq = subQuestions[i].trim()
    if (!sq) continue
    lines.push(`- [ ] Q${i + 1}. ${sq}`)
  }
  lines.push('')
  const content = lines.join('\n')
  fs.writeFileSync(p, content, 'utf-8')
  return content
}

/**
 * Parse plan.md checkboxes into a hierarchical structure.
 */
export function parsePlan(workspacePath: string): PlanItem[] {
  const p = planPath(workspacePath)
  if (!fs.existsSync(p)) return []
  const text = fs.readFileSync(p, 'utf-8')
  const lines = text.split('\n')
  const items: PlanItem[] = []
  const stack: { level: number; item: PlanItem }[] = []
  for (const raw of lines) {
    const m = raw.match(/^(\s*)-\s*\[([ xX])\]\s+(.*)$/)
    if (!m) continue
    const indent = Math.floor(m[1].length / 2)
    const done = m[2] !== ' '
    const text = m[3].trim()
    const id = text.match(/^([QA]\d+(\.\d+)*)\.?/)?.[1] || `item-${items.length}`
    const item: PlanItem = { id, text, done, level: indent, children: [] }
    while (stack.length && stack[stack.length - 1].level >= indent) stack.pop()
    if (stack.length === 0) items.push(item)
    else stack[stack.length - 1].item.children.push(item)
    stack.push({ level: indent, item })
  }
  return items
}

/**
 * Toggle a checkbox by item id in-place.
 */
export function updatePlanItem(workspacePath: string, itemId: string, done: boolean): boolean {
  const p = planPath(workspacePath)
  if (!fs.existsSync(p)) return false
  const text = fs.readFileSync(p, 'utf-8')
  const lines = text.split('\n')
  let changed = false
  const normalizedId = itemId.trim().toLowerCase()
  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i]
    const m = raw.match(/^(\s*)-\s*\[([ xX])\]\s+(.*)$/)
    if (!m) continue
    const bodyId = m[3].match(/^([QA]\d+(\.\d+)*)\.?/)?.[1]?.toLowerCase()
    if (bodyId === normalizedId || m[3].toLowerCase().startsWith(normalizedId)) {
      lines[i] = `${m[1]}- [${done ? 'x' : ' '}] ${m[3]}`
      changed = true
      break
    }
  }
  if (!changed) return false
  fs.writeFileSync(p, lines.join('\n'), 'utf-8')
  return true
}

export function planProgress(items: PlanItem[]): { total: number; done: number; pct: number } {
  let total = 0, done = 0
  const walk = (list: PlanItem[]) => {
    for (const it of list) {
      total++
      if (it.done) done++
      if (it.children.length) walk(it.children)
    }
  }
  walk(items)
  return { total, done, pct: total === 0 ? 0 : Math.round((done / total) * 100) }
}
